-- HD2-Addon: mods/alomare/better_chat
-- Better Chat by Alomare.
--
-- Quality of life for the game's text chat, each part set in Mod Options Menu (escape menu > MODS, optional):
-- - New message sound: when another player's chat line arrives, one of the game's own UI sounds plays, at most once
--   every 2 seconds. Your own lines and lines from players you muted don't count (the game doesn't store those).
-- - Chat size: the chat box and its text scale by the size set.
-- - Chat translation (opt-in, off by default): another player's line is sent to Google Translate's keyless endpoint
--   (translate.googleapis.com) by Windows' own curl.exe, started without a window; the line goes in through curl's
--   standard input and the reply comes back through a pipe read every frame, so the game never waits. A line in
--   another language than the game's Text Language is added to the chat, on this machine only, through the game's
--   own add-line, under the same sender. Nothing is sent anywhere while the option is off.
--
-- How: the chat keeps its last 64 lines in a ring (first index, line count, then 64 lines of sender, time and
-- text). Every 200 ms the mod reads the ring's first index and count (one small read); when lines were added, it
-- reads their senders and compares them with the local player's peer id. The sound goes through the game's UI sound
-- function, the size through the game's widget scale setter on the chat widget.
-- Everything native is found in game.dll by code signatures (first at this build's addresses, else by a search of
-- its executable sections spread over frames, where a signature must match exactly once), and structure offsets
-- are read from the matched code. A feature whose code is missing stays off; without the chat ring the mod does
-- nothing.
-- Status: %LOCALAPPDATA%\CowboyBingus\Helldivers2\Logs\BetterChat_STATUS.log (first line = verdict).
if rawget(_G, 'BetterChat') then return end

local ffi = require('ffi')

local M = {version = '3', frames = 0, errors = 0}
rawset(_G, 'BetterChat', M)

local loader = rawget(_G, 'CowboyBingusModLoader')

---------------------------------------------------------------------------------------
-- The game's code

-- BEGIN SIGNATURES (generated by research/signatures.py; game.dll build 25480438 addresses)
local SIGS = {
    {name = 'chat_send', rva = 0x186025d, text = '48 8B 0D ?? ?? ?? ?? 4C 8D 87 D4 16 00 00 48 81 C1 ?? ?? ?? ?? E8 ?? ?? ?? ?? BA ?? ?? ?? ?? E8 ?? ?? ?? ??',
     fields = {context = {'rip', {3}, {7}}, chat = {'u32', {17}}, ui_sound = {'call', {32}, {36}}, send_sound = {'u32', {27}}}},
    {name = 'chat_ring', rva = 0x10979dc, text = '48 8B 05 ?? ?? ?? ?? 48 89 74 24 70 4C 89 64 24 38 4C 89 7C 24 30 45 33 FF 4C 8B A0 ?? ?? ?? ?? 41 8B F7 49 3B D4 74 ?? 44 8B 81 88 0B 00 00 41 8B D7 45 85 C0 0F 84 ?? ?? ?? ?? 66 0F 1F 84 00 00 00 00 00 8B C2 48 8D 77 08 48 69 C8 B8 00 00 00 48 03 F1 4C 39 36 74 ?? FF C2 41 3B D0 72 ?? E9 ?? ?? ?? ?? 48 85 F6 0F 84 ?? ?? ?? ?? 44 38 BE AC 00 00 00 0F 85 ?? ?? ?? ?? 48 8B 0D ?? ?? ?? ?? 45 33 C9 45 33 C0 C7 44 24 20 05 00 00 00 49 8B D6 E8 ?? ?? ?? ?? 84 C0 0F 85 ?? ?? ?? ?? 8B 87 ?? ?? ?? ?? 8B 8F ?? ?? ?? ?? 48 89 5C 24 60 48 89 6C 24 68 8D 14 01 83 E2 3F 83 F8 40 75 ?? 8D 41 01 83 E0 3F 89 87 ?? ?? ?? ?? EB ?? FF C0 89 87 ?? ?? ?? ?? 48 8B 1D ?? ?? ?? ?? 8B C2 48 69 E8 ?? ?? ?? ??',
     fields = {context = {'rip', {3}, {7}}, local_peer = {'u32', {28}}, ring_first = {'u32', {168, 201}}, ring_count = {'u32', {162, 211}}, line_stride = {'u32', {227}}, game_state = {'rip', {218}, {222}}}},
    {name = 'chat_line', rva = 0x1097b37, text = '4C 89 B4 2F ?? ?? ?? ?? 48 03 C1 48 89 84 2F ?? ?? ?? ?? 4D 3B F4 74 ?? 8B 86 A8 00 00 00 89 84 2F B0 0D 00 00 8B 86 A8 00 00 00 85 C0 75 ?? 4C 8B BE 90 00 00 00 EB ?? 83 F8 01 75 ?? 4C 8B BE 98 00 00 00 EB ?? 83 F8 04 75 ?? 4C 8B BE A0 00 00 00 48 8B 0D ?? ?? ?? ?? 49 8B D6 4C 89 BC 2F A8 0D 00 00 E8 ?? ?? ?? ?? 88 84 2F A1 0D 00 00 66 C7 84 2F A4 0D 00 00 00 00 66 C7 84 2F A4 0D 00 00 01 01 48 8D 9F ?? ?? ?? ?? 48 8B 05 ?? ?? ?? ?? 48 03 DD 4D 8B C5 4C 3B B0 ?? ?? ?? ?? 75 ?? 41 B9 01 02 00 00 48 8B CB 41 8B D1 E8 ?? ?? ?? ?? EB ?? 48 8B 05 ?? ?? ?? ?? 80 B8 94 24 00 00 00 74 ??',
     fields = {line_sender = {'u32', {4}}, line_time = {'u32', {15}}, line_text = {'u32', {135}}, context = {'rip', {142}, {146}}, local_peer = {'u32', {155}}}},
    {name = 'join_feed', rva = 0x12f21fe, text = '48 8B 2D ?? ?? ?? ?? 48 8B FA 80 BD ?? ?? ?? ?? 00 0F 84 ?? ?? ?? ?? 48 8B 0D ?? ?? ?? ?? 49 89 5B 08 4D 89 73 18 8B 91 ?? ?? ?? ?? 83 EA 03 74 ?? 83 FA 01 75 ?? BA ?? ?? ?? ?? EB ?? BA ?? ?? ?? ?? E8 ?? ?? ?? ??',
     fields = {hud = {'rip', {3}, {7}}, hud_active = {'u32', {12}}, game_state = {'rip', {26}, {30}}, mode = {'u32', {40}}, join_mission = {'u32', {55}}, join_ship = {'u32', {62}}, ui_sound = {'call', {67}, {71}}}},
    {name = 'leave_feed', rva = 0x12f26d5, optional = true, text = '48 8B 05 ?? ?? ?? ?? 44 8B 88 ?? ?? ?? ?? 41 83 F8 08 74 ?? 41 83 E9 03 74 ?? 41 83 F9 01 75 ?? BA ?? ?? ?? ?? EB ?? BA ?? ?? ?? ?? E8 ?? ?? ?? ??',
     fields = {game_state = {'rip', {3}, {7}}, mode = {'u32', {10}}, leave_mission = {'u32', {33}}, leave_ship = {'u32', {40}}, ui_sound = {'call', {45}, {49}}}},
    {name = 'chat_notice', rva = 0x12f2f81, text = '48 8B 3D ?? ?? ?? ?? 49 8B F0 48 8B DA 80 BF ?? ?? ?? ?? 00 0F 84 ?? ?? ?? ?? 4C 8B 1D ?? ?? ?? ?? 33 C0 49 39 1B 74 ?? FF C0 49 81 C3 C0 00 00 00 83 F8 08 72 ?? E9 ?? ?? ?? ?? 0F 1F 40 00 0F 29 74 24 70 48 8D 54 24 50 0F 28 35 ?? ?? ?? ?? 4C 8B C3 E8 ?? ?? ?? ?? 4D 8D 4B 08 48 89 74 24 28 48 8D 8F 80 70 4F 00 66 0F 7F 74 24 40 4C 8D 44 24 40 BA 7F 03 12 1C 0F 10 00 48 8D 44 24 30 48 89 44 24 20 0F 29 44 24 30 E8 ?? ?? ?? ?? F3 0F 10 15 ?? ?? ?? ?? 48 8D 8F ?? ?? ?? ?? 48 8B D0 E8 ?? ?? ?? ??',
     fields = {hud = {'rip', {3}, {7}}, hud_active = {'u32', {15}}, chat_hud = {'u32', {154}}}},
    {name = 'tab_button', rva = 0x17ae42c, optional = true, text = 'C7 81 40 0D 00 00 ?? ?? ?? ?? 33 D2 C7 81 44 0D 00 00 ?? ?? ?? ??',
     fields = {tab_hover = {'u32', {6}}, tab_click = {'u32', {18}}}},
    {name = 'button_sounds', rva = 0x14a47d0, optional = true, text = '66 C7 01 00 00 48 8B C1 C7 41 04 ?? ?? ?? ?? C7 41 08 ?? ?? ?? ??',
     fields = {button_hover = {'u32', {11}}, button_click = {'u32', {18}}}},
    {name = 'option_row', rva = 0x17fde75, optional = true, text = 'BA ?? ?? ?? ?? 75 ?? BA ?? ?? ?? ?? E8 ?? ?? ?? ?? BA FF FF FF FF 48 8B CB 48 83 C4 20',
     fields = {option_click = {'u32', {1}}, option_refused = {'u32', {8}}, ui_sound = {'call', {13}, {17}}}},
    {name = 'chat_input', rva = 0x18608d0, optional = true, text = '48 83 EC 28 80 B9 ?? ?? ?? ?? 00 4C 8B C9 74 ?? 84 D2 74 ?? E8 ?? ?? ?? ?? 84 C0 74 ?? 33 D2 49 8B C9',
     fields = {chat_open = {'u32', {6}}}},
    {name = 'chat_field', rva = 0x1860200, optional = true, text = '48 8B D3 48 8D 8F ?? ?? ?? ?? E8 ?? ?? ?? ?? 0F B6 87 0F 1E 00 00 40 88 AF 0F 1E 00 00',
     fields = {chat_field = {'u32', {6}}, field_update = {'call', {11}, {15}}}},
    {name = 'field_text', rva = 0x18f2ef8, optional = true, text = '44 8B 93 ?? ?? ?? ?? 48 8D 4C 24 40 41 FF CA E8 ?? ?? ?? ?? 48 8D 4C 24 40 8B D0 41 3B C2 72 ?? 41 8B D2 E8 ?? ?? ?? ?? 8B C8 48 8D 54 24 40 C6 44 0C 40 00 48 8D 8B ?? ?? ?? ?? E8 ?? ?? ?? ?? 48 8B CB E8 ?? ?? ?? ?? 80 BB 76 0A 00 00 00',
     fields = {field_max = {'u32', {3}}, field_widget = {'u32', {55}}, set_text_call = {'call', {60}, {64}}}},
    {name = 'set_text', rva = 0x143dd60, optional = true, text = '48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 20 48 85 D2 48 8D 3D ?? ?? ?? ?? 48 8B D9 48 0F 45 FA BA 48 06 00 00 48 8B CF E8 ?? ?? ?? ?? 48 3D ?? ?? ?? ?? 73 ?? 41 B8 ?? ?? ?? ?? 48 8D 8B ?? ?? ?? ?? 48 8B D7 E8 ?? ?? ?? ??',
     fields = {text_limit = {'u32', {47, 55}}, widget_text = {'u32', {62}}}},
    {name = 'play_sound', rva = 0x1327f50, text = '48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 20 48 8B 05 ?? ?? ?? ?? 8B DA 48 8B 0D ?? ?? ?? ?? 48 8B 90 88 02 00 00 48 8B 89 F8 10 00 00 48 8B B0 38 03 00 00',
     fields = {}},
    {name = 'add_line', rva = 0x10979c0, optional = true, text = '40 57 41 55 41 56 48 83 EC 40 80 39 00 4D 8B E8 4C 8B F2 48 8B F9 0F 84 ?? ?? ?? ??',
     fields = {}},
    {name = 'set_scale', rva = 0x1447ed0, optional = true, text = '48 89 5C 24 18 48 89 6C 24 20 48 89 54 24 10 56 57 41 57 48 83 EC 20 F3 0F 10 41 14',
     fields = {}},
}
-- END SIGNATURES

-- BEGIN SIGNATURE ENGINE (tools/sigscan.lua, written by research/signatures.py: edit it there)
-- Signature engine v1: finds game.dll code by signatures and reads values from the matched code.
-- Canonical copy: tools/sigscan.lua in the workspace. Each mod's research/signatures.py writes this block and the
-- mod's SIGS table into its script (tools/sigspec.py), so every mod carries the same engine.
--
-- A signature is {name, rva, text, fields, optional}: text is hex bytes with '??' wildcards; rva is where the
-- generating build had it. fields = {field = {kind, {offset...}, {next...}}}: kind 'u8' / 'u32' (a value inside the
-- matched code), 'rip' (a global: the target of a rip-relative operand) or 'call' (a function: the target of a rel32
-- call); offset = each occurrence's byte position in the pattern, next = the end of its instruction. Every occurrence
-- must agree, and a field shared by several signatures must agree across them.
--
--   local code = sigscan.new(SIGS, read, base, validate)  -- read(address, size) -> string or nil; base = game.dll
--                                                        -- base; validate (optional) = {name = function(rva) -> bool}:
--                                                        -- extra checks a match must pass (decoys don't count)
--   code:start()                                 -- tries each signature at its rva; true when all were there
--   code:step()                                  -- else: one chunk of the search per call; true when finished
--   code.found[name] (rva), code.missing[name] (reason), code.values[field], code.problems (list)
local sigscan = {}
do
    local CHUNK, OVERLAP = 0x400000, 256

    local function u16(b, o) return b:byte(o + 1) + 256 * b:byte(o + 2) end
    local function u32(b, o)
        local x1, x2, x3, x4 = b:byte(o + 1, o + 4)
        return x1 + 256 * x2 + 65536 * x3 + 16777216 * x4
    end
    local function i32(b, o)
        local v = u32(b, o)
        return v >= 2147483648 and v - 4294967296 or v
    end

    local function parse(sig)
        local bytes = {}
        for part in sig.text:gmatch('%S+') do bytes[#bytes + 1] = part ~= '??' and tonumber(part, 16) or false end
        local best_at, best_len, at, len = 1, 0, nil, 0  -- the longest run of fixed bytes is searched for
        for i = 1, #bytes + 1 do
            if bytes[i] then
                if not at then at, len = i, 0 end
                len = len + 1
                if len > best_len then best_at, best_len = at, len end
            else
                at = nil
            end
        end
        local anchor = {}
        for i = best_at, best_at + best_len - 1 do anchor[#anchor + 1] = string.char(bytes[i]) end
        sig.bytes, sig.anchor, sig.anchor_at = bytes, table.concat(anchor), best_at - 1
    end

    local function matches(blob, pos, sig)  -- pos: 1-based start in blob
        local bytes = sig.bytes
        if pos < 1 or pos + #bytes - 1 > #blob then return false end
        for i = 1, #bytes do
            local b = bytes[i]
            if b and blob:byte(pos + i - 1) ~= b then return false end
        end
        return true
    end

    local Scanner = {}
    Scanner.__index = Scanner

    function sigscan.new(sigs, read, base, validate)
        return setmetatable({sigs = sigs, read = read, base = base, validate = validate or {}, found = {}, missing = {},
                             moved = {}, values = {}, problems = {}, scan = nil, done = false}, Scanner)
    end

    function Scanner:valid(name, rva)
        local check = self.validate[name]
        if not check then return true end
        local ok, good = pcall(check, rva)
        return ok and good and true or false
    end

    -- game.dll's sections: {rva, size, exec}.
    function Scanner:load_sections()
        local read, base = self.read, self.base
        local dos = read(base, 0x40)
        local pe = dos and dos:sub(1, 2) == 'MZ' and u32(dos, 0x3c)
        local nt = pe and pe < 0x10000 and read(base + pe, 0x18)
        if not nt or nt:sub(1, 4) ~= 'PE\0\0' then return nil end
        local count, opt = u16(nt, 6), u16(nt, 20)
        local headers = count <= 96 and read(base + pe + 24 + opt, count * 40)
        if not headers then return nil end
        local sections = {}
        for i = 0, count - 1 do
            local size, rva, flags = u32(headers, i * 40 + 8), u32(headers, i * 40 + 12), u32(headers, i * 40 + 36)
            if size > 0 then
                sections[#sections + 1] = {rva = rva, size = size, exec = math.floor(flags / 0x20000000) % 2 == 1}
            end
        end
        return sections
    end

    function Scanner:in_section(rva, exec)
        for _, s in ipairs(self.sections) do
            if s.exec == exec and rva >= s.rva and rva + 8 <= s.rva + s.size then return true end
        end
        return false
    end

    -- Tries every signature at its rva and starts a search for the others. True when all were there (done), false
    -- when a search started, nil and a reason when game.dll is unreadable.
    function Scanner:start()
        self.sections = self:load_sections()
        if not self.sections then return nil, 'game.dll headers unreadable' end
        local wanted = {}
        for _, sig in ipairs(self.sigs) do
            parse(sig)
            local blob = self.read(self.base + sig.rva, #sig.bytes)
            if blob and matches(blob, 1, sig) and self:valid(sig.name, sig.rva) then
                self.found[sig.name] = sig.rva
            else
                wanted[#wanted + 1] = sig
            end
        end
        if #wanted == 0 then
            self:resolve()
            return true
        end
        local exec = {}
        for _, s in ipairs(self.sections) do if s.exec then exec[#exec + 1] = s end end
        self.scan = {sections = exec, section = 1, offset = 0, wanted = wanted, hits = {}}
        for _, sig in ipairs(wanted) do self.scan.hits[sig.name] = {} end
        return false
    end

    -- One chunk of the search (every match is collected: a signature must match exactly once). True when finished.
    function Scanner:step()
        local scan = self.scan
        if not scan then return true end
        local s = scan.sections[scan.section]
        if s then
            local from = scan.offset
            local size = math.min(CHUNK + OVERLAP, s.size - from)
            local pieces = {}
            local blob = self.read(self.base + s.rva + from, size)
            if blob then
                pieces[1] = {from, blob}
            else
                for off = from, from + size - 1, 0x10000 do  -- skip unreadable pages
                    local piece = self.read(self.base + s.rva + off, math.min(0x10000 + OVERLAP, s.size - off))
                    if piece then pieces[#pieces + 1] = {off, piece} end
                end
            end
            for _, piece in ipairs(pieces) do
                local piece_from, data = piece[1], piece[2]
                for _, sig in ipairs(scan.wanted) do
                    local init = 1
                    while true do
                        local at = data:find(sig.anchor, init, true)
                        if not at then break end
                        local start = at - sig.anchor_at
                        local offset = piece_from + start - 1
                        -- Matches starting in the overlap belong to the next chunk.
                        if offset >= from and offset < from + CHUNK and matches(data, start, sig)
                           and self:valid(sig.name, s.rva + offset) then
                            local hits = scan.hits[sig.name]
                            hits[#hits + 1] = s.rva + offset
                        end
                        init = at + 1
                    end
                end
            end
            scan.offset = from + CHUNK
            if scan.offset >= s.size then scan.section, scan.offset = scan.section + 1, 0 end
            if scan.sections[scan.section] then return false end
        end
        for _, sig in ipairs(scan.wanted) do
            local hits = scan.hits[sig.name]
            if #hits == 1 then
                self.found[sig.name] = hits[1]
                self.moved[#self.moved + 1] = sig.name
            else
                self.missing[sig.name] = #hits == 0 and 'not found' or ('found ' .. #hits .. ' times')
            end
        end
        self.scan = nil
        self:resolve()
        return true
    end

    -- A field's value from the matched code; nil and a reason if its occurrences disagree or it points nowhere.
    function Scanner:field_value(sig, rva, spec)
        local blob = self.read(self.base + rva, #sig.bytes)
        if not blob then return nil, 'unreadable' end
        local value
        for k, off in ipairs(spec[2]) do
            local v
            if spec[1] == 'u8' then v = blob:byte(off + 1)
            elseif spec[1] == 'u32' then v = u32(blob, off)
            else v = rva + spec[3][k] + i32(blob, off) end
            if value and v ~= value then return nil, 'occurrences disagree' end
            value = v
        end
        if spec[1] == 'rip' and not self:in_section(value, false) then return nil, 'global not in a data section' end
        if spec[1] == 'call' and not self:in_section(value, true) then return nil, 'function not in a code section' end
        return value
    end

    -- Reads every field of the found signatures. A signature whose fields don't read becomes missing; a field that
    -- differs between signatures is dropped (nil) and listed in problems.
    function Scanner:resolve()
        local seen = {}
        for _, sig in ipairs(self.sigs) do
            local rva = self.found[sig.name]
            if rva then
                local got = {}
                for name, spec in pairs(sig.fields or {}) do
                    local v, why = self:field_value(sig, rva, spec)
                    if not v then
                        self.missing[sig.name] = string.format('field "%s" %s', name, why)
                        self.found[sig.name] = nil
                        got = nil
                        break
                    end
                    got[name] = v
                end
                for name, v in pairs(got or {}) do
                    if seen[name] ~= nil and seen[name] ~= v then
                        self.problems[#self.problems + 1] = string.format('"%s" differs between signatures', name)
                        seen[name] = false
                    elseif seen[name] == nil then
                        seen[name] = v
                    end
                end
            end
        end
        for name, v in pairs(seen) do self.values[name] = v or nil end
        self.done = true
    end

    -- The address of a found signature's match (plus an offset), or nil.
    function Scanner:address(name, offset)
        local rva = self.found[name]
        return rva and self.base + rva + (offset or 0)
    end

    -- Every missing signature as 'name (reason)', for logs and status files.
    function Scanner:missing_list()
        local out = {}
        for _, sig in ipairs(self.sigs) do
            if self.missing[sig.name] then out[#out + 1] = sig.name .. ' (' .. self.missing[sig.name] .. ')' end
        end
        return out
    end
end
-- END SIGNATURE ENGINE

---------------------------------------------------------------------------------------
-- Configuration

local OPTION = 'alomare.better_chat.'
local REQUIRED = {'chat_send', 'chat_ring', 'chat_line'}
local RING_SIZE = 64           -- chat history lines (the add-line's index mask is 0x3f)
local COOLDOWN = 2.0           -- seconds between two message sounds
local CHECK_EVERY = 0.2        -- seconds between two reads of the chat history
local MODE_MISSION = 4         -- game mode: 3 ship, 4 mission
-- The sound choice (Mod Options Menu index): the game's own UI sounds, read from the code that plays them; the HUD
-- notices have a value per game mode.
local SOUNDS = {
    {},                        -- OFF
    {key = 'choice.joined', sig = 'join_feed', ship = 'join_ship', mission = 'join_mission'},
    {key = 'choice.left', sig = 'leave_feed', ship = 'leave_ship', mission = 'leave_mission'},
    {key = 'choice.tab', sig = 'tab_button', ship = 'tab_click', mission = 'tab_click'},
    {key = 'choice.subtab', sig = 'button_sounds', ship = 'button_click', mission = 'button_click'},
    {key = 'choice.option', sig = 'option_row', ship = 'option_click', mission = 'option_click'},
}
local DEFAULTS = {sound = 2, scale = 100, paste = true, translate = false, translate_to = 1, translate_own = false}
local SCALE = {min = 50, max = 200, step = 5}
local SCALE_EVERY = 30         -- frames between size checks
local MAX_LOG_LINES = 2000
-- Translation: one curl process at a time, the lines waiting behind it in a short queue.
local ENDPOINT = 'https://translate.googleapis.com/translate_a/single?client=gtx&dt=t&sl=auto&tl='
local CURL_TIMEOUT = 8         -- seconds: curl's own limit for the request
local JOB_LIMIT = 12           -- seconds: a curl process still running then is ended
local RETRY_DELAY = 1          -- seconds before a server error or network failure is tried again (once)
local QUEUE_MAX = 8            -- lines waiting for translation (the oldest is dropped beyond)
local REPLY_MAX = 0x20000      -- bytes of a reply read at most
local SHOW_MAX = 0x1f0         -- bytes of a shown line (the game's line holds 0x200 and a NUL)
local MIN_LETTERS = 4          -- an ASCII-only line with fewer letters is not sent ("gg", "ez", "o7": misdetected)
-- Paste: the clipboard's text is added to the chat's text box.
local PASTE_MAX = 256          -- characters taken from the clipboard (the chat keeps fewer)
-- Translate To (Mod Options Menu index): Automatic (Windows' regional format, else its display language), the
-- game's Text Language, or one of the
-- game's languages (Google's codes; Spanish and Latin American Spanish are one language there).
local TRANSLATE_TO = {
    {key = 'choice.automatic'}, {key = 'choice.game'},
    {name = 'English', code = 'en'}, {name = 'Deutsch', code = 'de'}, {name = 'Español', code = 'es'},
    {name = 'Français', code = 'fr'}, {name = 'Italiano', code = 'it'}, {name = 'Polski', code = 'pl'},
    {name = 'Português (Brasil)', code = 'pt'}, {name = 'Português (Portugal)', code = 'pt-PT'},
    {name = 'Русский', code = 'ru'}, {name = '日本語', code = 'ja'}, {name = '한국어', code = 'ko'},
    {name = '简体中文', code = 'zh-CN'}, {name = '繁體中文', code = 'zh-TW'},
}

---------------------------------------------------------------------------------------
-- Logging and status

local function open_log(name)
    if loader and type(loader.open_log) == 'function' then
        local ok, f = pcall(loader.open_log, name)
        if ok then return f end
    end
end

local log_file = open_log('BetterChat.log')
local log_lines = 0

local function note(msg)
    if not log_file or log_lines >= MAX_LOG_LINES then return end
    log_lines = log_lines + 1
    pcall(function()
        log_file:write(string.format('[f%d t%.1f] %s\n', M.frames, os.clock(), msg))
        log_file:flush()
    end)
end

local function write_status(lines)
    local f = open_log('BetterChat_STATUS.log')
    if not f then return end
    pcall(function()
        f:write(table.concat(lines, '\n') .. '\n')
        f:close()
    end)
end

---------------------------------------------------------------------------------------
-- Texts (mod_text: src/bingus_text.lua and locales/, placed ahead of this script by the build)

local T = mod_text.module
local tr = T.new(mod_text.locales.en, mod_text.locales.bundled, function(message) note('Text: ' .. message) end)

-- Mod Options Menu v1.1+ (version 2) takes texts as functions and calls them when its pages open, so the texts
-- follow the game's language; v1.0 takes strings with limits, where a translation that does not fit stays English.
-- One function per key, so repeated registrations agree.
local text_functions = {}
local function host_text(host, functions_from, key, limit)
    if (tonumber(host.version) or 1) >= functions_from then
        local fn = text_functions[key]
        if not fn then fn = function() return tr(key) end; text_functions[key] = fn end
        return fn
    end
    local value = tr(key)
    return #value <= limit and value or tr.english[key]
end

---------------------------------------------------------------------------------------
-- Native access (Windows functions under this mod's own names: no other mod's declarations can change them)

local native = {}

local function init_native()
    if not pcall(ffi.typeof, 'BetterChatVec2') then
        ffi.cdef([[
            typedef struct { float x, y; } BetterChatVec2;
            typedef void (*BetterChatSound)(uint64_t unused, uint32_t id);
            typedef void (*BetterChatSetVec)(uint64_t widget, BetterChatVec2 value);
            typedef void (*BetterChatAddLine)(uint64_t chat, uint64_t sender, const char *text);
            typedef uint32_t (*BetterChatSetText)(uint64_t widget, const char *text);
            typedef struct { uint32_t nLength; void *lpSecurityDescriptor; int bInheritHandle; } BetterChatSA;
            typedef struct {
                uint32_t cb; uint16_t *lpReserved, *lpDesktop, *lpTitle;
                uint32_t dwX, dwY, dwXSize, dwYSize, dwXCountChars, dwYCountChars, dwFillAttribute, dwFlags;
                uint16_t wShowWindow, cbReserved2; uint8_t *lpReserved2;
                void *hStdInput, *hStdOutput, *hStdError;
            } BetterChatStartupInfo;
            typedef struct { BetterChatStartupInfo StartupInfo; void *lpAttributeList; } BetterChatStartupInfoEx;
            typedef struct { void *hProcess, *hThread; uint32_t dwProcessId, dwThreadId; } BetterChatProcessInfo;
            void *better_chat_GetCurrentProcess(void) __asm__("GetCurrentProcess");
            void *better_chat_GetModuleHandleA(const char *name) __asm__("GetModuleHandleA");
            int better_chat_ReadProcessMemory(void *process, const void *address, void *buffer, size_t size,
                                              size_t *done) __asm__("ReadProcessMemory");
            uint32_t better_chat_GetSystemDirectoryW(uint16_t *buffer, uint32_t size) __asm__("GetSystemDirectoryW");
            uint32_t better_chat_GetFileAttributesW(const uint16_t *path) __asm__("GetFileAttributesW");
            int better_chat_QueryPerformanceCounter(int64_t *count) __asm__("QueryPerformanceCounter");
            int better_chat_QueryPerformanceFrequency(int64_t *frequency) __asm__("QueryPerformanceFrequency");
            uint32_t better_chat_GetLastError(void) __asm__("GetLastError");
            int better_chat_CreatePipe(void **read, void **write, BetterChatSA *attributes, uint32_t size)
                __asm__("CreatePipe");
            int better_chat_SetHandleInformation(void *handle, uint32_t mask, uint32_t flags)
                __asm__("SetHandleInformation");
            int better_chat_InitializeProcThreadAttributeList(void *list, uint32_t count, uint32_t flags,
                                                             size_t *size) __asm__("InitializeProcThreadAttributeList");
            int better_chat_UpdateProcThreadAttribute(void *list, uint32_t flags, uintptr_t attribute, void *value,
                                                     size_t size, void *previous, size_t *returned)
                __asm__("UpdateProcThreadAttribute");
            void better_chat_DeleteProcThreadAttributeList(void *list) __asm__("DeleteProcThreadAttributeList");
            int better_chat_CreateProcessW(const uint16_t *application, uint16_t *command_line, void *process_attributes,
                                           void *thread_attributes, int inherit, uint32_t flags, void *environment,
                                           const uint16_t *directory, BetterChatStartupInfoEx *startup,
                                           BetterChatProcessInfo *info) __asm__("CreateProcessW");
            int better_chat_WriteFile(void *handle, const void *buffer, uint32_t size, uint32_t *done,
                                      void *overlapped) __asm__("WriteFile");
            int better_chat_ReadFile(void *handle, void *buffer, uint32_t size, uint32_t *done, void *overlapped)
                __asm__("ReadFile");
            int better_chat_PeekNamedPipe(void *pipe, void *buffer, uint32_t size, uint32_t *read, uint32_t *available,
                                          uint32_t *left) __asm__("PeekNamedPipe");
            uint32_t better_chat_WaitForSingleObject(void *handle, uint32_t milliseconds)
                __asm__("WaitForSingleObject");
            int better_chat_GetExitCodeProcess(void *process, uint32_t *code) __asm__("GetExitCodeProcess");
            int better_chat_TerminateProcess(void *process, uint32_t code) __asm__("TerminateProcess");
            int better_chat_CloseHandle(void *handle) __asm__("CloseHandle");
            uint32_t better_chat_GetCurrentProcessId(void) __asm__("GetCurrentProcessId");
            uint16_t better_chat_GetUserDefaultUILanguage(void) __asm__("GetUserDefaultUILanguage");
            int better_chat_GetUserDefaultLocaleName(uint16_t *name, int size) __asm__("GetUserDefaultLocaleName");
            int better_chat_LCIDToLocaleName(uint32_t lcid, uint16_t *name, int size, uint32_t flags)
                __asm__("LCIDToLocaleName");
            void *better_chat_GlobalLock(void *memory) __asm__("GlobalLock");
            int better_chat_GlobalUnlock(void *memory) __asm__("GlobalUnlock");
            size_t better_chat_GlobalSize(void *memory) __asm__("GlobalSize");
            int16_t better_chat_GetAsyncKeyState(int key) __asm__("GetAsyncKeyState");
            void *better_chat_GetForegroundWindow(void) __asm__("GetForegroundWindow");
            uint32_t better_chat_GetWindowThreadProcessId(void *window, uint32_t *process)
                __asm__("GetWindowThreadProcessId");
            int better_chat_OpenClipboard(void *owner) __asm__("OpenClipboard");
            int better_chat_CloseClipboard(void) __asm__("CloseClipboard");
            void *better_chat_GetClipboardData(uint32_t format) __asm__("GetClipboardData");
        ]])
    end
    local ok, k32 = pcall(ffi.load, 'kernel32')
    if not ok then return false, 'kernel32 unavailable' end
    native.k32, native.process = k32, k32.better_chat_GetCurrentProcess()
    local ok_user, user32 = pcall(ffi.load, 'user32')
    native.user32 = ok_user and user32 or nil
    local game = k32.better_chat_GetModuleHandleA('game.dll')
    if game == nil then return false, 'game.dll not loaded' end
    native.base = tonumber(ffi.cast('uint64_t', game))
    return true
end

local function read(address, size)
    local buf, got = ffi.new('uint8_t[?]', size), ffi.new('size_t[1]')
    if native.k32.better_chat_ReadProcessMemory(native.process, ffi.cast('const void *', address), buf, size, got) == 0
       or tonumber(got[0]) ~= size then
        return nil
    end
    return ffi.string(buf, size)
end

local function u32(blob, offset)
    offset = offset or 0
    if not blob or #blob < offset + 4 then return nil end
    local v = ffi.new('uint32_t[1]')
    ffi.copy(v, blob:sub(offset + 1, offset + 4), 4)
    return tonumber(v[0])
end

local function read32(address) return u32(read(address, 4)) end

local function pointer(blob)
    if not blob or #blob ~= 8 then return nil end
    local v = ffi.new('uint64_t[1]')
    ffi.copy(v, blob, 8)
    local a = tonumber(v[0])
    if a < 0x10000 or a >= 0x800000000000 then return nil end
    return a
end

local function hex(blob)
    if not blob then return 'unreadable' end
    return (blob:reverse():gsub('.', function(c) return string.format('%02x', c:byte()) end))
end

-- Two floats from their 8 bytes.
local function vec_values(blob)
    if not blob or #blob ~= 8 then return nil end
    local v = ffi.new('float[2]')
    ffi.copy(v, blob, 8)
    return tonumber(v[0]), tonumber(v[1])
end

---------------------------------------------------------------------------------------
-- Resolution: signatures -> values and the game's functions

local code = nil  -- the signature engine
local V = {}      -- values read from the matched code (offsets; globals and functions as rvas)
local fn = {}     -- the game's functions that were found
local features = {}  -- feature -> true, or the reason it is off

local function need(names, values)
    for _, name in ipairs(names) do
        if not code.found[name] then return 'code not found: ' .. name .. ' (' .. (code.missing[name] or '?') .. ')' end
    end
    for _, name in ipairs(values or {}) do
        if V[name] == nil then return 'value missing: ' .. name end
    end
end

local function finish_resolution()
    V = code.values
    local missing = code:missing_list()
    local why = need(REQUIRED, {'context', 'chat', 'local_peer', 'ring_first', 'ring_count', 'line_stride',
                                'line_sender'})
    if not why and V.ring_count ~= V.ring_first + 4 then why = 'the ring count does not follow its first index' end
    if not why and V.line_stride < 0x210 then why = 'the chat line is smaller than its text' end
    if why then
        note('Not available: ' .. why .. (#code.problems > 0 and ('; ' .. table.concat(code.problems, ', ')) or ''))
        write_status({'NOT AVAILABLE - ' .. why .. '; the game is unchanged', 'Better Chat ' .. M.version})
        M.retired = true
        return
    end
    if #code.problems > 0 then note('Signature problems: ' .. table.concat(code.problems, ', ')) end
    local base = native.base
    -- The sound: the UI sound function, found by its body and through the calls to it.
    local sound_why = need({'play_sound'})
    if not sound_why and V.ui_sound ~= code.found.play_sound then sound_why = 'the UI sound differs from its calls' end
    if not sound_why then fn.play_sound = ffi.cast('BetterChatSound', base + code.found.play_sound) end
    features.sound = sound_why or true
    -- The size: the chat widget inside the HUD and the widget scale setter.
    local scale_why = need({'chat_notice', 'set_scale'}, {'hud', 'chat_hud'})
    if not scale_why then fn.set_scale = ffi.cast('BetterChatSetVec', base + code.found.set_scale) end
    features.scale = scale_why or true
    -- Translation: curl.exe (found at start); showing a translation also needs the chat's add-line, which must be
    -- the function the chat ring's code is in.
    local show_why = need({'add_line'})
    if not show_why and code.found.add_line + 0x1c ~= code.found.chat_ring then
        show_why = 'the add-line is not where the chat ring is'
    end
    if not show_why then fn.add_line = ffi.cast('BetterChatAddLine', base + code.found.add_line) end
    features.show = show_why or true
    -- Paste: the chat widget's input-open byte (read from the code), and user32 for the keys, clipboard and window.
    local paste_why = need({'chat_input', 'chat_notice', 'chat_field', 'field_text', 'set_text'},
                           {'hud', 'chat_hud', 'chat_open', 'chat_field', 'field_max', 'field_widget', 'text_limit',
                            'widget_text'})
    if not paste_why and V.set_text_call ~= code.found.set_text then paste_why = 'the text setter differs from its call' end
    if not paste_why and not (V.field_update < code.found.field_text and code.found.field_text < V.field_update + 0x1000) then
        paste_why = 'the text input code is not in the text field update'
    end
    if not paste_why and not native.user32 then paste_why = 'user32 unavailable' end
    if not paste_why then fn.set_text = ffi.cast('BetterChatSetText', base + code.found.set_text) end
    features.paste = paste_why or true
    M.ready = true
    if #code.moved > 0 then note('Moved code found: ' .. table.concat(code.moved, ', ')) end
    if #missing > 0 then note('Optional code not found: ' .. table.concat(missing, ', ')) end
    local list = {}
    for _, name in ipairs({'sound', 'scale', 'translate', 'show', 'paste'}) do
        list[#list + 1] = name .. ' ' .. (features[name] == true and 'ready' or ('off (' .. features[name] .. ')'))
    end
    local sounds = {}
    for i = 2, #SOUNDS do
        local sound = SOUNDS[i]
        sounds[#sounds + 1] = string.format('%s %s', sound.key:sub(8),
            code.found[sound.sig] and string.format('0x%08x/0x%08x', V[sound.ship], V[sound.mission]) or 'missing')
    end
    note(string.format('Ready: chat = context + 0x%x, ring at +0x%x (stride 0x%x, sender +0x%x); %s; sounds: %s',
                       V.chat, V.ring_first, V.line_stride, V.line_sender, table.concat(list, ', '),
                       table.concat(sounds, ', ')))
    write_status({'OK - watching the chat; ' .. table.concat(list, ', '), 'Better Chat ' .. M.version})
end

---------------------------------------------------------------------------------------
-- Settings (Mod Options Menu, optional; it may load before or after this addon). Without it: the defaults.

local options = {}
for k, v in pairs(DEFAULTS) do options[k] = v end
local menu_state = {menu = nil}
local scale_dirty = true

local function play(choice, why)
    local sound = SOUNDS[choice]
    if not (sound and sound.sig and features.sound == true and code.found[sound.sig]) then return false end
    local state = pointer(read(native.base + V.game_state, 8))
    local mode = state and V.mode and read32(state + V.mode)
    local id = V[mode == MODE_MISSION and sound.mission or sound.ship]
    if not id then return false end
    fn.play_sound(0, id)
    note(string.format('Sound 0x%08x (%s, mode %s)', id, why, tostring(mode)))
    return true
end

local function clamp(v, range, default)
    return math.max(range.min, math.min(range.max, tonumber(v) or default))
end

local SETTERS = {
    sound = function(v) v = math.floor(tonumber(v) or DEFAULTS.sound); return (v >= 1 and v <= #SOUNDS) and v or DEFAULTS.sound end,
    scale = function(v) return clamp(v, SCALE, DEFAULTS.scale) end,
    paste = function(v) return v ~= false end,
    translate = function(v) return v == true end,
    translate_to = function(v) v = math.floor(tonumber(v) or 1); return (v >= 1 and v <= #TRANSLATE_TO) and v or 1 end,
    translate_own = function(v) return v == true end,
}

local function set_option(name, value, applied)
    local v = SETTERS[name](value)
    if v ~= options[name] then note(string.format('Option %s = %s', name, tostring(v))) end
    options[name] = v
    if name == 'scale' then scale_dirty = true end
    -- A sound picked in the menu plays once, so it can be heard.
    if name == 'sound' and applied and M.ready then play(v, 'preview') end
end

local function connect_options()
    local menu = rawget(_G, 'ModOptionsMenu')
    if type(menu) ~= 'table' or menu.api ~= 1 then return end
    menu_state.menu = menu
    local function text(key, limit) return host_text(menu, 2, key, limit) end
    local mod = text('option.mod', 40)
    local choices = {}
    for i, sound in ipairs(SOUNDS) do choices[i] = i == 1 and 'OFF' or text(sound.key, 48) end
    local languages = {}
    for i, choice in ipairs(TRANSLATE_TO) do languages[i] = choice.name or text(choice.key, 48) end
    local specs = {
        {'sound', {type = 'choice', choices = choices, default = DEFAULTS.sound}},
        {'scale', {type = 'slider', min = SCALE.min, max = SCALE.max, step = SCALE.step, default = DEFAULTS.scale}},
        {'paste', {type = 'toggle', default = true}},
        {'translate', {type = 'toggle', default = false}},
        {'translate_to', {type = 'choice', choices = languages, default = 1}},
        {'translate_own', {type = 'toggle', default = false}},
    }
    for _, entry in ipairs(specs) do
        local name, spec = entry[1], entry[2]
        local id = OPTION .. name
        spec.mod, spec.mod_id = mod, 'alomare.better_chat'
        spec.label = text('option.' .. name .. '.label', 64)
        spec.description = text('option.' .. name .. '.description', 400)
        local ok, done, why = pcall(menu.register_option, id, spec)
        if ok and done then
            pcall(menu.on_change, id, function(value) set_option(name, value, true) end)
            local got, value = pcall(menu.get, id)
            if got and value ~= nil then set_option(name, value, false) end
        else
            note('Option ' .. id .. ' not registered: ' .. tostring(ok and why or done))
        end
    end
    note('Mod Options Menu connected (version ' .. tostring(menu.version or 1) .. ')')
end

---------------------------------------------------------------------------------------
-- Translation (opt-in): Windows' curl.exe asks Google Translate's keyless endpoint, one line at a time. The line goes
-- to curl's standard input (never on its command line); the reply comes back through a pipe read every frame.

local translate = {queue = {}, show = {}, job = nil, curl = nil, dir = nil, freq = nil, serial = 0}

-- A minimal JSON reader (the endpoint's reply is nested arrays of strings, numbers and nulls). Raises on bad input.
local json_value
do
    local ESCAPES = {['"'] = '"', ['\\'] = '\\', ['/'] = '/', b = '\b', f = '\f', n = '\n', r = '\r', t = '\t'}

    local function utf8_char(cp)
        if cp < 0x80 then return string.char(cp) end
        if cp < 0x800 then return string.char(0xc0 + math.floor(cp / 0x40), 0x80 + cp % 0x40) end
        if cp >= 0xd800 and cp <= 0xdfff then cp = 0xfffd end  -- a lone surrogate
        if cp < 0x10000 then
            return string.char(0xe0 + math.floor(cp / 0x1000), 0x80 + math.floor(cp / 0x40) % 0x40, 0x80 + cp % 0x40)
        end
        return string.char(0xf0 + math.floor(cp / 0x40000), 0x80 + math.floor(cp / 0x1000) % 0x40,
                           0x80 + math.floor(cp / 0x40) % 0x40, 0x80 + cp % 0x40)
    end

    local function skip(s, i) return s:find('[^ \t\r\n]', i) or #s + 1 end

    local function json_string(s, i)  -- s:sub(i, i) is the opening quote
        local out, j = {}, i + 1
        while true do
            local at = s:find('["\\]', j)
            if not at then error('unterminated string') end
            out[#out + 1] = s:sub(j, at - 1)
            if s:sub(at, at) == '"' then return table.concat(out), at + 1 end
            local e = s:sub(at + 1, at + 1)
            if e == 'u' then
                local cp = tonumber(s:sub(at + 2, at + 5), 16)
                if not cp or #s:sub(at + 2, at + 5) ~= 4 then error('bad \\u escape') end
                j = at + 6
                if cp >= 0xd800 and cp <= 0xdbff and s:sub(j, j + 1) == '\\u' then
                    local low = tonumber(s:sub(j + 2, j + 5), 16)
                    if low and low >= 0xdc00 and low <= 0xdfff then
                        cp, j = 0x10000 + (cp - 0xd800) * 0x400 + (low - 0xdc00), j + 6
                    end
                end
                out[#out + 1] = utf8_char(cp)
            elseif ESCAPES[e] then
                out[#out + 1], j = ESCAPES[e], at + 2
            else
                error('bad escape')
            end
        end
    end

    -- Returns the value and the position after it; null is nil (an array keeps its positions).
    function json_value(s, i, depth)
        depth = depth or 0
        if depth > 32 then error('too deep') end
        i = skip(s, i or 1)
        local c = s:sub(i, i)
        if c == '"' then return json_string(s, i) end
        if c == '[' or c == '{' then
            local close, out, n = c == '[' and ']' or '}', {}, 0
            i = skip(s, i + 1)
            if s:sub(i, i) == close then return out, i + 1 end
            while true do
                local key, v
                if close == '}' then
                    if s:sub(i, i) ~= '"' then error('bad object key') end
                    key, i = json_string(s, i)
                    i = skip(s, i)
                    if s:sub(i, i) ~= ':' then error('missing colon') end
                    i = i + 1
                end
                v, i = json_value(s, i, depth + 1)
                n = n + 1
                out[key or n] = v
                i = skip(s, i)
                local sep = s:sub(i, i)
                if sep == close then return out, i + 1 end
                if sep ~= ',' then error('missing comma') end
                i = skip(s, i + 1)
            end
        end
        for word, v in pairs({['true'] = true, ['false'] = false, null = 'null'}) do
            if s:sub(i, i + #word - 1) == word then
                if v == 'null' then return nil, i + #word end
                return v, i + #word
            end
        end
        local number = s:match('^-?%d+%.?%d*[eE]?[-+]?%d*', i)
        if number and tonumber(number) then return tonumber(number), i + #number end
        error('unexpected character at ' .. i)
    end
end

-- The translated text and the detected language from the endpoint's reply: [[[part, original, ...], ...], nil,
-- "es", ...].
local function parse_reply(body)
    local ok, data = pcall(json_value, body)
    if not ok then return nil, 'bad reply (' .. tostring(data) .. ')' end
    if type(data) ~= 'table' or type(data[1]) ~= 'table' then return nil, 'unexpected reply' end
    local parts = {}
    for i = 1, #data[1] do
        local part = data[1][i]
        if type(part) == 'table' and type(part[1]) == 'string' then parts[#parts + 1] = part[1] end
    end
    if #parts == 0 then return nil, 'no translation in the reply' end
    return table.concat(parts), type(data[3]) == 'string' and data[3] or nil
end

-- Google's code for a language tag ('pt-BR', 'zh-Hant', 'pt-PT', 'nl-NL'...): Portuguese other than Brazil's is
-- pt-PT, Chinese is zh-CN or zh-TW by script or region, any other tag gives its language.
local function google_code(tag)
    tag = tostring(tag or '')
    local language = (tag:match('^(%a%a%a?)') or ''):lower()
    local rest = tag:sub(#language + 1)
    if language == '' then return nil end
    if language == 'pt' then return (rest == '' or rest:match('^%-BR')) and 'pt' or 'pt-PT' end
    if language == 'zh' then return (rest:match('Hant') or rest:match('^%-TW') or rest:match('^%-HK') or rest:match('^%-MO'))
                                    and 'zh-TW' or 'zh-CN' end
    return language
end

local function locale_name(name, n)
    if n <= 1 then return nil end
    local chars = {}
    for i = 0, n - 2 do
        if name[i] >= 0x80 then return nil end
        chars[#chars + 1] = string.char(name[i])
    end
    return table.concat(chars)
end

-- Windows' regional format ('pt-BR': often the player's language when Windows itself is in English) and display
-- language, as tags (nil when unreadable).
local function windows_languages()
    local k = native.k32
    local name = ffi.new('uint16_t[85]')
    local region = locale_name(name, k.better_chat_GetUserDefaultLocaleName(name, 85))
    local display = locale_name(name, k.better_chat_LCIDToLocaleName(k.better_chat_GetUserDefaultUILanguage(), name, 85, 0))
    return region, display
end

-- Google's code for the Translate To setting.
local function target_language()
    local choice = TRANSLATE_TO[options.translate_to] or TRANSLATE_TO[1]
    if choice.code then return choice.code end
    if choice.key == 'choice.automatic' then
        local code = google_code(translate.region) or google_code(translate.display)
        if code then return code end
    end
    return google_code(T.language()) or 'en'
end

local function same_language(source, target)
    source, target = source:lower(), target:lower()
    if source == target then return true end
    local a, b = source:match('^%a+'), target:match('^%a+')
    return a == b and a ~= 'zh'  -- Simplified and Traditional Chinese are different scripts
end

-- The first bytes of a UTF-8 text, never splitting a character.
local function utf8_cut(s, max)
    if #s <= max then return s end
    local cut = max
    while cut > 0 and s:byte(cut + 1) >= 0x80 and s:byte(cut + 1) < 0xc0 do cut = cut - 1 end
    return s:sub(1, cut)
end

local function quoted(s) return '"' .. s:gsub('[%c]', ' ') .. '"' end

-- An ASCII text as a NUL-terminated UTF-16 buffer.
local function wide(s)
    local buf = ffi.new('uint16_t[?]', #s + 1)
    for i = 1, #s do buf[i - 1] = s:byte(i) end
    return buf
end

local function now()  -- seconds, from the performance counter
    local t = ffi.new('int64_t[1]')
    native.k32.better_chat_QueryPerformanceCounter(t)
    return tonumber(t[0]) / translate.freq
end

local function close(handle)
    if handle ~= nil then native.k32.better_chat_CloseHandle(handle) end
end

-- Finds Windows' curl.exe (System32; Windows 10 1803 and later). True, or false and the reason.
local function find_curl()
    local k = native.k32
    local freq = ffi.new('int64_t[1]')
    if k.better_chat_QueryPerformanceFrequency(freq) == 0 or tonumber(freq[0]) <= 0 then
        return false, 'no performance counter'
    end
    translate.freq = tonumber(freq[0])
    local buf = ffi.new('uint16_t[260]')
    local n = k.better_chat_GetSystemDirectoryW(buf, 260)
    if n == 0 or n >= 260 then return false, 'system folder unreadable' end
    local chars = {}
    for i = 0, n - 1 do
        if buf[i] >= 0x80 then return false, 'system folder name is not ASCII' end
        chars[#chars + 1] = string.char(buf[i])
    end
    local dir = table.concat(chars)
    local path = dir .. '\\curl.exe'
    local attributes = k.better_chat_GetFileAttributesW(wide(path))
    if attributes == 0xffffffff or math.floor(attributes / 16) % 2 == 1 then
        return false, 'curl.exe not found in ' .. dir
    end
    translate.curl, translate.dir = path, dir
    return true
end

-- Starts curl for one line: true, or nil and the reason.
local function spawn(entry)
    local k = native.k32
    local sa = ffi.new('BetterChatSA')
    sa.nLength, sa.bInheritHandle = ffi.sizeof(sa), 1
    local in_r, in_w, out_r, out_w = ffi.new('void *[1]'), ffi.new('void *[1]'), ffi.new('void *[1]'),
                                     ffi.new('void *[1]')
    if k.better_chat_CreatePipe(in_r, in_w, sa, 0x1000) == 0 then return nil, 'CreatePipe failed' end
    if k.better_chat_CreatePipe(out_r, out_w, sa, 0x10000) == 0 then
        close(in_r[0]); close(in_w[0])
        return nil, 'CreatePipe failed'
    end
    -- This process's ends are not inherited; curl gets only its own two ends (a handle list, when available).
    k.better_chat_SetHandleInformation(in_w[0], 1, 0)
    k.better_chat_SetHandleInformation(out_r[0], 1, 0)
    local si = ffi.new('BetterChatStartupInfoEx')
    si.StartupInfo.cb = ffi.sizeof(si)
    si.StartupInfo.dwFlags = 0x100  -- STARTF_USESTDHANDLES
    si.StartupInfo.hStdInput, si.StartupInfo.hStdOutput, si.StartupInfo.hStdError = in_r[0], out_w[0], out_w[0]
    local flags = 0x08000000  -- CREATE_NO_WINDOW
    local size = ffi.new('size_t[1]')
    k.better_chat_InitializeProcThreadAttributeList(nil, 1, 0, size)
    local list = tonumber(size[0]) > 0 and ffi.new('uint8_t[?]', tonumber(size[0]))
    local handles = ffi.new('void *[2]', in_r[0], out_w[0])
    if list and k.better_chat_InitializeProcThreadAttributeList(list, 1, 0, size) ~= 0 then
        if k.better_chat_UpdateProcThreadAttribute(list, 0, 0x20002, handles, ffi.sizeof(handles), nil, nil) ~= 0 then
            si.lpAttributeList, flags = list, flags + 0x80000  -- PROC_THREAD_ATTRIBUTE_HANDLE_LIST, EXTENDED_STARTUPINFO
        else
            k.better_chat_DeleteProcThreadAttributeList(list)
            list = nil
        end
    else
        list = nil
    end
    -- -sS: errors only; -w: the HTTP status after the body. The command line holds only this mod's constants.
    local command = string.format('"%s" -sS -m %d --max-filesize %d -G --data-urlencode q@- -w "\\n@@ %%{http_code}" '
                                  .. '"%s%s"', translate.curl, CURL_TIMEOUT, REPLY_MAX, ENDPOINT, entry.target)
    local info = ffi.new('BetterChatProcessInfo')
    local t0 = now()
    local ok = k.better_chat_CreateProcessW(wide(translate.curl), wide(command), nil, nil, 1, flags, nil,
                                            wide(translate.dir), si, info)
    local spawn_ms = (now() - t0) * 1000
    local err = ok == 0 and k.better_chat_GetLastError() or 0
    if list then k.better_chat_DeleteProcThreadAttributeList(list) end
    close(in_r[0]); close(out_w[0])
    if ok == 0 then
        close(in_w[0]); close(out_r[0])
        return nil, 'CreateProcess failed (error ' .. tostring(err) .. ')'
    end
    close(info.hThread)
    local done = ffi.new('uint32_t[1]')
    k.better_chat_WriteFile(in_w[0], entry.text, #entry.text, done, nil)  -- fits the pipe: never waits
    close(in_w[0])
    translate.job = {entry = entry, process = info.hProcess, out = out_r[0], started = t0, spawn_ms = spawn_ms,
                     chunks = {}, size = 0}
    return true
end

-- Reads what curl wrote so far; 'done' once it exited (everything read), 'timeout' when it was ended.
local function poll(job)
    local k = native.k32
    local exited = k.better_chat_WaitForSingleObject(job.process, 0) == 0
    local available, got = ffi.new('uint32_t[1]'), ffi.new('uint32_t[1]')
    while job.size < REPLY_MAX and k.better_chat_PeekNamedPipe(job.out, nil, 0, nil, available, nil) ~= 0
          and available[0] > 0 do
        local n = math.min(tonumber(available[0]), REPLY_MAX - job.size)
        local buf = ffi.new('uint8_t[?]', n)
        if k.better_chat_ReadFile(job.out, buf, n, got, nil) == 0 or got[0] == 0 then break end
        job.chunks[#job.chunks + 1] = ffi.string(buf, got[0])
        job.size = job.size + got[0]
    end
    if exited then return 'done' end
    if now() - job.started > JOB_LIMIT then
        k.better_chat_TerminateProcess(job.process, 1)
        return 'timeout'
    end
end

local function finish(job, how)
    local entry = job.entry
    local exit_code = ffi.new('uint32_t[1]')
    native.k32.better_chat_GetExitCodeProcess(job.process, exit_code)
    close(job.process); close(job.out)
    translate.job = nil
    local ms = (now() - job.started) * 1000
    local out = table.concat(job.chunks)
    local at, _, status = out:find('\n@@ (%d+)%s*$')
    local body = at and out:sub(1, at - 1) or out
    local head = string.format('Translation %d (%.0f ms, start %.1f ms)', entry.id, ms, job.spawn_ms)
    if how == 'timeout' or exit_code[0] ~= 0 or status ~= '200' then
        -- curl's own error message only (never the reply, which can hold the line).
        note(string.format('%s failed: %s, curl exit %d, HTTP %s%s', head, how, exit_code[0], tostring(status),
                           exit_code[0] ~= 0 and (': ' .. quoted(body:sub(1, 120))) or ''))
        -- A server error or a network failure is tried once more, a second later.
        local transient = how ~= 'timeout' and (exit_code[0] ~= 0 or (status or ''):match('^5'))
        if transient and not entry.retried and options.translate then
            entry.retried, entry.not_before = true, now() + RETRY_DELAY
            table.insert(translate.queue, 1, entry)
            note('Translation ' .. entry.id .. ' will be retried')
        end
        return
    end
    local text, source = parse_reply(body)
    if not text then
        note(string.format('%s failed: %s', head, source))
        return
    end
    source = source or '?'
    note(string.format('%s %s -> %s', head, source, entry.target))
    if same_language(source, entry.target) then
        note('Translation ' .. entry.id .. ' not shown: already in ' .. entry.target)
    elseif text:lower() == entry.text:lower() then
        note('Translation ' .. entry.id .. ' not shown: same as the line')
    elseif features.show ~= true then
        note('Translation ' .. entry.id .. ' not shown: ' .. tostring(features.show))
    else
        local label = '[' .. (source:match('^%a+') or source):upper() .. '] '
        translate.show[#translate.show + 1] = {id = entry.id, sender = entry.sender,
                                               text = utf8_cut(label .. text:gsub('%c', ' '), SHOW_MAX)}
    end
end

-- A chat line to translate (sender: its 8 bytes as read).
local function enqueue(sender, text)
    if not options.translate or features.translate ~= true or text == '' then return end
    if not text:find('[\128-\255]') and select(2, text:gsub('%a', '')) < MIN_LETTERS then
        note('Line not translated: too short')
        return
    end
    translate.serial = translate.serial + 1
    if #translate.queue >= QUEUE_MAX then
        note('Translation ' .. translate.queue[1].id .. ' dropped (queue full)')
        table.remove(translate.queue, 1)
    end
    translate.queue[#translate.queue + 1] = {id = translate.serial, sender = sender, text = text,
                                             target = target_language()}
end

-- One step per frame: reads the running curl, else starts the next line.
local function pump()
    if translate.job then
        local how = poll(translate.job)
        if how then finish(translate.job, how) end
        return
    end
    if not options.translate then
        if #translate.queue > 0 then translate.queue = {} end
        return
    end
    local entry = translate.queue[1]
    if not entry or (entry.not_before and now() < entry.not_before) then return end
    table.remove(translate.queue, 1)
    local ok, why = spawn(entry)
    if not ok then note('Translation ' .. entry.id .. ' not started: ' .. why) end
end

---------------------------------------------------------------------------------------
-- New chat lines

local ring = {ctx = nil, first = 0, count = 0}
local clock, last_sound, last_check = 0, -math.huge, -math.huge

local function alert(others, total)
    note(string.format('%d new chat line(s), %d from other players', total, others))
    if others == 0 or options.sound == 1 then return end
    if clock - last_sound >= COOLDOWN then
        if play(options.sound, 'new message') then last_sound = clock end
    else
        note('Sound skipped (cooldown)')
    end
end

-- The chat line flags the game keeps per line, after the sender and text (diagnostics): friend, shown, filtered,
-- and two display bytes.
local LINE_FLAGS = 0x209       -- from the sender (0xda1 - 0xb98 in this build)
local function line_flags(chat, slot)
    local b = read(chat + V.line_sender + LINE_FLAGS + slot * V.line_stride, 5)
    if not b then return '?' end
    return string.format('%d%d%d%d%d', b:byte(1, 5))
end

local function watch_chat()
    local ctx = pointer(read(native.base + V.context, 8))
    if not ctx then
        if ring.ctx then note('Network context gone'); ring.ctx = nil end
        return
    end
    local chat = ctx + V.chat
    local header = read(chat + V.ring_first, 8)
    local first, count = u32(header, 0), u32(header, 4)
    if not first or first >= RING_SIZE or count > RING_SIZE then return end
    if ring.ctx ~= ctx or count < ring.count then
        -- A new session or a cleared history: lines already there are not new.
        note(string.format('Chat history: context 0x%x, first %d, count %d', ctx, first, count))
        ring.ctx, ring.first, ring.count = ctx, first, count
        return
    end
    local new = (count - ring.count) + (first - ring.first) % RING_SIZE
    ring.first, ring.count = first, count
    if new <= 0 then return end
    new = math.min(new, RING_SIZE)
    local own = read(ctx + V.local_peer, 8)
    local others = 0
    for k = new, 1, -1 do
        local slot = (first + count - k) % RING_SIZE
        local sender = read(chat + V.line_sender + slot * V.line_stride, 8)
        local text = read(chat + V.line_text + slot * V.line_stride, 0x200)
        local length = text and (text:find('\0', 1, true) or 0x201) - 1 or -1
        local from_other = sender ~= nil and own ~= nil and sender ~= own
        if from_other then others = others + 1 end
        note(string.format('Line %d: sender %s%s, %d bytes, flags %s', slot, hex(sender),
                           from_other and '' or ' (you)', length, line_flags(chat, slot)))
        if sender and length > 0 and (from_other or options.translate_own) then enqueue(sender, text:sub(1, length)) end
    end
    alert(others, new)
end

-- Adds the finished translations to the chat through the game's add-line (on this machine only), right after a
-- check of the chat, then takes the history as it is now: the added lines are not new messages.
local function show_translations()
    watch_chat()
    local ctx = ring.ctx
    for _, entry in ipairs(translate.show) do
        if ctx and pointer(read(native.base + V.context, 8)) == ctx then
            local sender = ffi.new('uint64_t[1]')
            ffi.copy(sender, entry.sender, 8)
            fn.add_line(ctx + V.chat, sender[0], entry.text)
            note('Translation ' .. entry.id .. ' shown')
        else
            note('Translation ' .. entry.id .. ' not shown: the chat changed')
        end
    end
    translate.show = {}
    if not ctx then return end
    local header = read(ctx + V.chat + V.ring_first, 8)
    local first, count = u32(header, 0), u32(header, 4)
    if first and first < RING_SIZE and count <= RING_SIZE then ring.first, ring.count = first, count end
end

---------------------------------------------------------------------------------------
-- Chat size

local layout = {scale_base = nil, scaled = false, logged = false}

local function near(a, b) return math.abs(a - b) < 1e-4 end

local function apply_scale()
    local hud = pointer(read(native.base + V.hud, 8))
    if not hud then return end
    local widget = hud + V.chat_hud
    local sx, sy = vec_values(read(widget + 0x14, 8))
    -- A widget not laid out yet has scale 0: wait for it.
    if not sx or sx <= 0 or sy <= 0 then return end
    if not layout.logged then
        layout.logged = true
        note(string.format('Chat widget 0x%x: scale (%.3f, %.3f)', widget, sx, sy))
    end
    if not layout.scaled then layout.scale_base = {sx, sy} end
    local want = options.scale / 100
    local wx, wy = layout.scale_base[1] * want, layout.scale_base[2] * want
    if (layout.scaled or options.scale ~= 100) and not (near(sx, wx) and near(sy, wy)) then
        fn.set_scale(widget, ffi.new('BetterChatVec2', wx, wy))
        layout.scaled = options.scale ~= 100
        note(string.format('Chat scale (%.3f, %.3f) -> (%.3f, %.3f)', sx, sy, wx, wy))
    end
end

---------------------------------------------------------------------------------------
-- Paste: Ctrl+V while the chat's text input is open. The clipboard's text is added to the end of the chat's text
-- through the game's own text setter (the one its Steam text input uses); the chat's next update applies its own
-- character limit. The engine's typed characters cannot be fed from here (posted WM_CHAR never reached them, 3-3).
-- Line breaks and tabs become spaces; other control characters and characters outside the Basic Multilingual
-- Plane (emoji) are left out.

local paste = {v_down = false}

-- The foreground window is the game's (this process's).
local function game_in_front()
    local u = native.user32
    local window = u.better_chat_GetForegroundWindow()
    if window == nil then return false end
    local pid = ffi.new('uint32_t[1]')
    u.better_chat_GetWindowThreadProcessId(window, pid)
    return pid[0] == native.k32.better_chat_GetCurrentProcessId()
end

local function utf8_unit(c)  -- a UTF-16 code unit outside the surrogates
    if c < 0x80 then return string.char(c) end
    if c < 0x800 then return string.char(0xc0 + math.floor(c / 0x40), 0x80 + c % 0x40) end
    return string.char(0xe0 + math.floor(c / 0x1000), 0x80 + math.floor(c / 0x40) % 0x40, 0x80 + c % 0x40)
end

-- The clipboard's text as UTF-8, cleaned for one chat line, or nil and the reason.
local function clipboard_text()
    local u, k = native.user32, native.k32
    if u.better_chat_OpenClipboard(nil) == 0 then return nil, 'clipboard busy' end
    local out, count, why = {}, 0, nil
    local data = u.better_chat_GetClipboardData(13)  -- CF_UNICODETEXT
    local text = data ~= nil and k.better_chat_GlobalLock(data) or nil
    if text == nil then
        why = 'no text in the clipboard'
    else
        local chars = ffi.cast('const uint16_t *', text)
        local limit = math.floor(tonumber(k.better_chat_GlobalSize(data)) / 2)
        local space = false
        for i = 0, limit - 1 do
            local c = chars[i]
            if c == 0 or count >= PASTE_MAX then break end
            if c == 9 or c == 10 or c == 13 or c == 32 or c == 0xa0 then
                if not space and count > 0 then out[#out + 1], count = ' ', count + 1 end
                space = true
            elseif c >= 0x20 and c ~= 0x7f and (c < 0xd800 or c > 0xdfff) then
                out[#out + 1], count, space = utf8_unit(c), count + 1, false
            end
        end
        while out[#out] == ' ' do out[#out] = nil end
        k.better_chat_GlobalUnlock(data)
    end
    u.better_chat_CloseClipboard()
    if why then return nil, why end
    if #out == 0 then return nil, 'nothing to type in the clipboard' end
    return table.concat(out)
end

-- The first `chars` characters of a UTF-8 text, within `bytes` bytes.
local function utf8_head(s, chars, bytes)
    local at, n = 1, 0
    while at <= #s and n < chars do
        local b = s:byte(at)
        local size = b < 0x80 and 1 or b < 0xe0 and 2 or b < 0xf0 and 3 or 4
        if at + size - 1 > bytes then break end
        at, n = at + size, n + 1
    end
    return s:sub(1, at - 1)
end

local function paste_step()
    local u = native.user32
    -- Ctrl+V: V pressed this frame (async key state, so it works however the game reads its keys) with Ctrl held.
    local v_down = u.better_chat_GetAsyncKeyState(0x56) < 0
    local pressed = v_down and not paste.v_down
    paste.v_down = v_down
    if not (pressed and u.better_chat_GetAsyncKeyState(0x11) < 0) then return end
    local hud = pointer(read(native.base + V.hud, 8))
    local widget = hud and hud + V.chat_hud
    local open = widget and read(widget + V.chat_open, 1)
    if not (open and open:byte() ~= 0) or not game_in_front() then return end
    local added, why = clipboard_text()
    if not added then note('Paste: ' .. why); return end
    local field = widget + V.chat_field
    local text_widget = field + V.field_widget
    local current = read(text_widget + V.widget_text, V.text_limit)
    current = current and current:match('^[^%z]*') or ''
    -- The field keeps (limit - 1) characters; the setter refuses text_limit bytes or more.
    local limit = read32(field + V.field_max)
    local chars = (limit and limit > 1 and limit <= V.text_limit) and limit - 1 or V.text_limit
    local text = utf8_head(current .. added, chars, V.text_limit - 1)
    local changed = fn.set_text(text_widget, text)
    note(string.format('Paste: %d bytes added (limit %s characters)%s', #text - #current, tostring(limit and limit - 1),
                       changed ~= 0 and '' or ', text unchanged'))
end

---------------------------------------------------------------------------------------
-- Frame step

local function start()
    M.started = true
    local ok, why = init_native()
    if not ok then
        write_status({'NOT AVAILABLE - ' .. why .. '; the game is unchanged', 'Better Chat ' .. M.version})
        note('Native access unavailable: ' .. why)
        M.retired = true
        return
    end
    -- The game's Text Language, for this mod's texts and every other mod's (bingus_text's shared registry).
    local tag, game_code = T.observe(read, native.base)
    note('Text language: ' .. tostring(T.language()) .. ' (game setting ' .. tostring(game_code or 'unreadable')
         .. ', tag ' .. tostring(tag) .. ')')
    local curl_ok, curl_why = find_curl()
    features.translate = curl_ok or curl_why
    note('Translation: ' .. (curl_ok and ('curl at ' .. translate.curl) or ('off, ' .. curl_why)))
    translate.region, translate.display = windows_languages()
    note(string.format('Windows: regional format %s, display language %s (Automatic: %s)', tostring(translate.region),
                       tostring(translate.display), tostring(google_code(translate.region) or google_code(translate.display))))
    code = sigscan.new(SIGS, read, native.base)
    local all, reason = code:start()
    if all == nil then
        write_status({'NOT AVAILABLE - ' .. reason .. '; the game is unchanged', 'Better Chat ' .. M.version})
        M.retired = true
    elseif all then
        finish_resolution()
    else
        note('Searching game.dll for moved code (game updated?)')
    end
end

local function frame(dt)
    M.frames = M.frames + 1
    clock = clock + (tonumber(dt) or 0)
    if not menu_state.menu then connect_options() end
    if not M.started then start(); return end
    if not M.ready then
        if code.scan and code:step() then finish_resolution() end
        return
    end
    if clock - last_check >= CHECK_EVERY then
        last_check = clock
        watch_chat()
    end
    if features.paste == true and options.paste then paste_step() end
    if features.translate == true then
        pump()
        if #translate.show > 0 then show_translations() end
    end
    if features.scale == true and (scale_dirty or M.frames % SCALE_EVERY == 0) then
        scale_dirty = false
        apply_scale()
    end
end

local original_update = rawget(_G, 'update')
update = function(dt, ...)
    if not M.retired then
        local ok, err = xpcall(frame, debug.traceback, dt)
        if not ok then
            M.errors = M.errors + 1
            note('Error: ' .. tostring(err))
            if M.errors >= 5 then
                M.retired = true
                write_status({'STOPPED - repeated errors (see BetterChat.log)', 'Better Chat ' .. M.version})
            end
        end
    end
    if type(original_update) == 'function' then return original_update(dt, ...) end
end

note('Better Chat ' .. M.version .. ' loaded')
M._test = {values = function() return V end, features = function() return features end,
           options = function() return options end, json = function(s) return (json_value(s)) end, google_code = google_code,
           reread_windows = function() translate.region, translate.display = windows_languages() end,
           translate = translate}  -- offline checks
return M
