-- HD2-Addon: mods/alomare/better_chat
-- Better Chat by Alomare.
--
-- Quality of life for the game's text chat, each part set in Mod Options Menu (escape menu > MODS, optional):
-- - New message sound: when another player's chat line arrives, one of the game's own UI sounds plays, at most once
--   every 2 seconds. Your own lines and lines from players you muted don't count (the game doesn't store those).
-- - New message volume: that sound, louder or quieter than the game plays it.
-- - Chat size: the chat box and its text scale by the size set.
--
-- How: the chat keeps its last 64 lines in a ring (first index, line count, then 64 lines of sender, time and
-- text). Every 200 ms the mod reads the ring's first index and count (one small read); when lines were added, it
-- reads their senders and compares them with the local player's peer id. The sound goes through the game's UI sound
-- function, the size through the game's widget scale setter on the chat widget. At another volume the mod does what
-- that sound function does (a new sound source in the game's Wwise world, the event posted on it), with the source's
-- own level set in between through the engine's Lua API (WwiseWorld.set_dry_environment_for_source).
-- Everything native is found in game.dll by code signatures (first at this build's addresses, else by a search of
-- its executable sections spread over frames, where a signature must match exactly once), and structure offsets
-- are read from the matched code. A feature whose code is missing stays off; without the chat ring the mod does
-- nothing.
-- Status: %LOCALAPPDATA%\CowboyBingus\Helldivers2\Logs\BetterChat_STATUS.log (first line = verdict).
if rawget(_G, 'BetterChat') then return end

local ffi = require('ffi')

local M = {version = '2-recon-1', frames = 0, errors = 0}
rawset(_G, 'BetterChat', M)

local loader = rawget(_G, 'CowboyBingusModLoader')

---------------------------------------------------------------------------------------
-- The game's code

-- BEGIN SIGNATURES (generated by research/signatures.py; game.dll build 25480438 addresses)
local SIGS = {
    {name = 'chat_send', rva = 0x186025d, text = '48 8B 0D ?? ?? ?? ?? 4C 8D 87 D4 16 00 00 48 81 C1 ?? ?? ?? ?? E8 ?? ?? ?? ?? BA ?? ?? ?? ?? E8 ?? ?? ?? ??',
     fields = {context = {'rip', {3}, {7}}, chat = {'u32', {17}}, ui_sound = {'call', {32}, {36}}, send_sound = {'u32', {27}}}},
    {name = 'chat_ring', rva = 0x10979dc, text = '48 8B 05 ?? ?? ?? ?? 48 89 74 24 70 4C 89 64 24 38 4C 89 7C 24 30 45 33 FF 4C 8B A0 ?? ?? ?? ?? 41 8B F7 49 3B D4 74 ?? 44 8B 81 88 0B 00 00 41 8B D7 45 85 C0 0F 84 ?? ?? ?? ?? 66 0F 1F 84 00 00 00 00 00 8B C2 48 8D 77 08 48 69 C8 B8 00 00 00 48 03 F1 4C 39 36 74 ?? FF C2 41 3B D0 72 ?? E9 ?? ?? ?? ?? 48 85 F6 0F 84 ?? ?? ?? ?? 44 38 BE AC 00 00 00 0F 85 ?? ?? ?? ?? 48 8B 0D ?? ?? ?? ?? 45 33 C9 45 33 C0 C7 44 24 20 05 00 00 00 49 8B D6 E8 ?? ?? ?? ?? 84 C0 0F 85 ?? ?? ?? ?? 8B 87 ?? ?? ?? ?? 8B 8F ?? ?? ?? ?? 48 89 5C 24 60 48 89 6C 24 68 8D 14 01 83 E2 3F 83 F8 40 75 ?? 8D 41 01 83 E0 3F 89 87 ?? ?? ?? ?? EB ?? FF C0 89 87 ?? ?? ?? ?? 48 8B 1D ?? ?? ?? ?? 8B C2 48 69 E8 ?? ?? ?? ??',
     fields = {context = {'rip', {3}, {7}}, local_peer = {'u32', {28}}, ring_first = {'u32', {168, 201}}, ring_count = {'u32', {162, 211}}, line_stride = {'u32', {227}}, game_state = {'rip', {218}, {222}}}},
    {name = 'chat_line', rva = 0x1097b37, text = '4C 89 B4 2F ?? ?? ?? ?? 48 03 C1 48 89 84 2F ?? ?? ?? ?? 4D 3B F4 74 ?? 8B 86 A8 00 00 00 89 84 2F B0 0D 00 00 8B 86 A8 00 00 00 85 C0 75 ?? 4C 8B BE 90 00 00 00 EB ?? 83 F8 01 75 ?? 4C 8B BE 98 00 00 00 EB ?? 83 F8 04 75 ?? 4C 8B BE A0 00 00 00 48 8B 0D ?? ?? ?? ?? 49 8B D6 4C 89 BC 2F A8 0D 00 00 E8 ?? ?? ?? ?? 88 84 2F A1 0D 00 00 66 C7 84 2F A4 0D 00 00 00 00 66 C7 84 2F A4 0D 00 00 01 01 48 8D 9F ?? ?? ?? ?? 48 8B 05 ?? ?? ?? ?? 48 03 DD 4D 8B C5 4C 3B B0 ?? ?? ?? ?? 75 ?? 41 B9 01 02 00 00 48 8B CB 41 8B D1 E8 ?? ?? ?? ?? EB ?? 48 8B 05 ?? ?? ?? ?? 80 B8 94 24 00 00 00 74 ??',
     fields = {line_sender = {'u32', {4}}, line_time = {'u32', {15}}, line_text = {'u32', {135}}, context = {'rip', {142}, {146}}, local_peer = {'u32', {155}}}},
    {name = 'join_feed', rva = 0x12f21fe, text = '48 8B 2D ?? ?? ?? ?? 48 8B FA 80 BD ?? ?? ?? ?? 00 0F 84 ?? ?? ?? ?? 48 8B 0D ?? ?? ?? ?? 49 89 5B 08 4D 89 73 18 8B 91 ?? ?? ?? ?? 83 EA 03 74 ?? 83 FA 01 75 ?? BA ?? ?? ?? ?? EB ?? BA ?? ?? ?? ?? E8 ?? ?? ?? ??',
     fields = {hud = {'rip', {3}, {7}}, hud_active = {'u32', {12}}, game_state = {'rip', {26}, {30}}, mode = {'u32', {40}}, join_mission = {'u32', {55}}, join_ship = {'u32', {62}}, ui_sound = {'call', {67}, {71}}}},
    {name = 'leave_feed', rva = 0x12f26d5, optional = true, text = '48 8B 05 ?? ?? ?? ?? 44 8B 88 ?? ?? ?? ?? 41 83 F8 08 74 ?? 41 83 E9 03 74 ?? 41 83 F9 01 75 ?? BA ?? ?? ?? ?? EB ?? BA ?? ?? ?? ?? E8 ?? ?? ?? ??',
     fields = {game_state = {'rip', {3}, {7}}, mode = {'u32', {10}}, leave_mission = {'u32', {33}}, leave_ship = {'u32', {40}}, ui_sound = {'call', {45}, {49}}}},
    {name = 'chat_notice', rva = 0x12f2f81, text = '48 8B 3D ?? ?? ?? ?? 49 8B F0 48 8B DA 80 BF ?? ?? ?? ?? 00 0F 84 ?? ?? ?? ?? 4C 8B 1D ?? ?? ?? ?? 33 C0 49 39 1B 74 ?? FF C0 49 81 C3 C0 00 00 00 83 F8 08 72 ?? E9 ?? ?? ?? ?? 0F 1F 40 00 0F 29 74 24 70 48 8D 54 24 50 0F 28 35 ?? ?? ?? ?? 4C 8B C3 E8 ?? ?? ?? ?? 4D 8D 4B 08 48 89 74 24 28 48 8D 8F 80 70 4F 00 66 0F 7F 74 24 40 4C 8D 44 24 40 BA 7F 03 12 1C 0F 10 00 48 8D 44 24 30 48 89 44 24 20 0F 29 44 24 30 E8 ?? ?? ?? ?? F3 0F 10 15 ?? ?? ?? ?? 48 8D 8F ?? ?? ?? ?? 48 8B D0 E8 ?? ?? ?? ??',
     fields = {hud = {'rip', {3}, {7}}, hud_active = {'u32', {15}}, chat_hud = {'u32', {154}}}},
    {name = 'tab_button', rva = 0x17ae42c, optional = true, text = 'C7 81 40 0D 00 00 ?? ?? ?? ?? 33 D2 C7 81 44 0D 00 00 ?? ?? ?? ??',
     fields = {tab_hover = {'u32', {6}}, tab_click = {'u32', {18}}}},
    {name = 'button_sounds', rva = 0x14a47d0, optional = true, text = '66 C7 01 00 00 48 8B C1 C7 41 04 ?? ?? ?? ?? C7 41 08 ?? ?? ?? ??',
     fields = {button_hover = {'u32', {11}}, button_click = {'u32', {18}}}},
    {name = 'option_row', rva = 0x17fde75, optional = true, text = 'BA ?? ?? ?? ?? 75 ?? BA ?? ?? ?? ?? E8 ?? ?? ?? ?? BA FF FF FF FF 48 8B CB 48 83 C4 20',
     fields = {option_click = {'u32', {1}}, option_refused = {'u32', {8}}, ui_sound = {'call', {13}, {17}}}},
    {name = 'play_sound', rva = 0x1327f50, text = '48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 20 48 8B 05 ?? ?? ?? ?? 8B DA 48 8B 0D ?? ?? ?? ?? 48 8B 90 88 02 00 00 48 8B 89 F8 10 00 00 48 8B B0 38 03 00 00',
     fields = {}},
    {name = 'ui_post', rva = 0x1327f5f, optional = true, text = '48 8B 05 ?? ?? ?? ?? 8B DA 48 8B 0D ?? ?? ?? ?? 48 8B 90 ?? ?? ?? ?? 48 8B 89 ?? ?? ?? ?? 48 8B B0 ?? ?? ?? ?? FF D2 8B CB 48 8B F8 E8 ?? ?? ?? ?? 48 8B 0D ?? ?? ?? ?? 45 33 C9 4C 8B C7 8B D0',
     fields = {engine = {'rip', {3}, {7}}, game_state = {'rip', {12, 52}, {16, 56}}, make_source = {'u32', {19}}, ui_world = {'u32', {26}}, post_event = {'u32', {33}}, audio_id = {'call', {45}, {49}}}},
    {name = 'set_scale', rva = 0x1447ed0, optional = true, text = '48 89 5C 24 18 48 89 6C 24 20 48 89 54 24 10 56 57 41 57 48 83 EC 20 F3 0F 10 41 14',
     fields = {}},
}
-- END SIGNATURES

-- BEGIN SIGNATURE ENGINE (tools/sigscan.lua, written by research/signatures.py: edit it there)
-- Signature engine v1: finds game.dll code by signatures and reads values from the matched code.
-- Canonical copy: tools/sigscan.lua in the workspace. Each mod's research/signatures.py writes this block and the
-- mod's SIGS table into its script (tools/sigspec.py), so every mod carries the same engine.
--
-- A signature is {name, rva, text, fields, optional}: text is hex bytes with '??' wildcards; rva is where the
-- generating build had it. fields = {field = {kind, {offset...}, {next...}}}: kind 'u8' / 'u32' (a value inside the
-- matched code), 'rip' (a global: the target of a rip-relative operand) or 'call' (a function: the target of a rel32
-- call); offset = each occurrence's byte position in the pattern, next = the end of its instruction. Every occurrence
-- must agree, and a field shared by several signatures must agree across them.
--
--   local code = sigscan.new(SIGS, read, base, validate)  -- read(address, size) -> string or nil; base = game.dll
--                                                        -- base; validate (optional) = {name = function(rva) -> bool}:
--                                                        -- extra checks a match must pass (decoys don't count)
--   code:start()                                 -- tries each signature at its rva; true when all were there
--   code:step()                                  -- else: one chunk of the search per call; true when finished
--   code.found[name] (rva), code.missing[name] (reason), code.values[field], code.problems (list)
local sigscan = {}
do
    local CHUNK, OVERLAP = 0x400000, 256

    local function u16(b, o) return b:byte(o + 1) + 256 * b:byte(o + 2) end
    local function u32(b, o)
        local x1, x2, x3, x4 = b:byte(o + 1, o + 4)
        return x1 + 256 * x2 + 65536 * x3 + 16777216 * x4
    end
    local function i32(b, o)
        local v = u32(b, o)
        return v >= 2147483648 and v - 4294967296 or v
    end

    local function parse(sig)
        local bytes = {}
        for part in sig.text:gmatch('%S+') do bytes[#bytes + 1] = part ~= '??' and tonumber(part, 16) or false end
        local best_at, best_len, at, len = 1, 0, nil, 0  -- the longest run of fixed bytes is searched for
        for i = 1, #bytes + 1 do
            if bytes[i] then
                if not at then at, len = i, 0 end
                len = len + 1
                if len > best_len then best_at, best_len = at, len end
            else
                at = nil
            end
        end
        local anchor = {}
        for i = best_at, best_at + best_len - 1 do anchor[#anchor + 1] = string.char(bytes[i]) end
        sig.bytes, sig.anchor, sig.anchor_at = bytes, table.concat(anchor), best_at - 1
    end

    local function matches(blob, pos, sig)  -- pos: 1-based start in blob
        local bytes = sig.bytes
        if pos < 1 or pos + #bytes - 1 > #blob then return false end
        for i = 1, #bytes do
            local b = bytes[i]
            if b and blob:byte(pos + i - 1) ~= b then return false end
        end
        return true
    end

    local Scanner = {}
    Scanner.__index = Scanner

    function sigscan.new(sigs, read, base, validate)
        return setmetatable({sigs = sigs, read = read, base = base, validate = validate or {}, found = {}, missing = {},
                             moved = {}, values = {}, problems = {}, scan = nil, done = false}, Scanner)
    end

    function Scanner:valid(name, rva)
        local check = self.validate[name]
        if not check then return true end
        local ok, good = pcall(check, rva)
        return ok and good and true or false
    end

    -- game.dll's sections: {rva, size, exec}.
    function Scanner:load_sections()
        local read, base = self.read, self.base
        local dos = read(base, 0x40)
        local pe = dos and dos:sub(1, 2) == 'MZ' and u32(dos, 0x3c)
        local nt = pe and pe < 0x10000 and read(base + pe, 0x18)
        if not nt or nt:sub(1, 4) ~= 'PE\0\0' then return nil end
        local count, opt = u16(nt, 6), u16(nt, 20)
        local headers = count <= 96 and read(base + pe + 24 + opt, count * 40)
        if not headers then return nil end
        local sections = {}
        for i = 0, count - 1 do
            local size, rva, flags = u32(headers, i * 40 + 8), u32(headers, i * 40 + 12), u32(headers, i * 40 + 36)
            if size > 0 then
                sections[#sections + 1] = {rva = rva, size = size, exec = math.floor(flags / 0x20000000) % 2 == 1}
            end
        end
        return sections
    end

    function Scanner:in_section(rva, exec)
        for _, s in ipairs(self.sections) do
            if s.exec == exec and rva >= s.rva and rva + 8 <= s.rva + s.size then return true end
        end
        return false
    end

    -- Tries every signature at its rva and starts a search for the others. True when all were there (done), false
    -- when a search started, nil and a reason when game.dll is unreadable.
    function Scanner:start()
        self.sections = self:load_sections()
        if not self.sections then return nil, 'game.dll headers unreadable' end
        local wanted = {}
        for _, sig in ipairs(self.sigs) do
            parse(sig)
            local blob = self.read(self.base + sig.rva, #sig.bytes)
            if blob and matches(blob, 1, sig) and self:valid(sig.name, sig.rva) then
                self.found[sig.name] = sig.rva
            else
                wanted[#wanted + 1] = sig
            end
        end
        if #wanted == 0 then
            self:resolve()
            return true
        end
        local exec = {}
        for _, s in ipairs(self.sections) do if s.exec then exec[#exec + 1] = s end end
        self.scan = {sections = exec, section = 1, offset = 0, wanted = wanted, hits = {}}
        for _, sig in ipairs(wanted) do self.scan.hits[sig.name] = {} end
        return false
    end

    -- One chunk of the search (every match is collected: a signature must match exactly once). True when finished.
    function Scanner:step()
        local scan = self.scan
        if not scan then return true end
        local s = scan.sections[scan.section]
        if s then
            local from = scan.offset
            local size = math.min(CHUNK + OVERLAP, s.size - from)
            local pieces = {}
            local blob = self.read(self.base + s.rva + from, size)
            if blob then
                pieces[1] = {from, blob}
            else
                for off = from, from + size - 1, 0x10000 do  -- skip unreadable pages
                    local piece = self.read(self.base + s.rva + off, math.min(0x10000 + OVERLAP, s.size - off))
                    if piece then pieces[#pieces + 1] = {off, piece} end
                end
            end
            for _, piece in ipairs(pieces) do
                local piece_from, data = piece[1], piece[2]
                for _, sig in ipairs(scan.wanted) do
                    local init = 1
                    while true do
                        local at = data:find(sig.anchor, init, true)
                        if not at then break end
                        local start = at - sig.anchor_at
                        local offset = piece_from + start - 1
                        -- Matches starting in the overlap belong to the next chunk.
                        if offset >= from and offset < from + CHUNK and matches(data, start, sig)
                           and self:valid(sig.name, s.rva + offset) then
                            local hits = scan.hits[sig.name]
                            hits[#hits + 1] = s.rva + offset
                        end
                        init = at + 1
                    end
                end
            end
            scan.offset = from + CHUNK
            if scan.offset >= s.size then scan.section, scan.offset = scan.section + 1, 0 end
            if scan.sections[scan.section] then return false end
        end
        for _, sig in ipairs(scan.wanted) do
            local hits = scan.hits[sig.name]
            if #hits == 1 then
                self.found[sig.name] = hits[1]
                self.moved[#self.moved + 1] = sig.name
            else
                self.missing[sig.name] = #hits == 0 and 'not found' or ('found ' .. #hits .. ' times')
            end
        end
        self.scan = nil
        self:resolve()
        return true
    end

    -- A field's value from the matched code; nil and a reason if its occurrences disagree or it points nowhere.
    function Scanner:field_value(sig, rva, spec)
        local blob = self.read(self.base + rva, #sig.bytes)
        if not blob then return nil, 'unreadable' end
        local value
        for k, off in ipairs(spec[2]) do
            local v
            if spec[1] == 'u8' then v = blob:byte(off + 1)
            elseif spec[1] == 'u32' then v = u32(blob, off)
            else v = rva + spec[3][k] + i32(blob, off) end
            if value and v ~= value then return nil, 'occurrences disagree' end
            value = v
        end
        if spec[1] == 'rip' and not self:in_section(value, false) then return nil, 'global not in a data section' end
        if spec[1] == 'call' and not self:in_section(value, true) then return nil, 'function not in a code section' end
        return value
    end

    -- Reads every field of the found signatures. A signature whose fields don't read becomes missing; a field that
    -- differs between signatures is dropped (nil) and listed in problems.
    function Scanner:resolve()
        local seen = {}
        for _, sig in ipairs(self.sigs) do
            local rva = self.found[sig.name]
            if rva then
                local got = {}
                for name, spec in pairs(sig.fields or {}) do
                    local v, why = self:field_value(sig, rva, spec)
                    if not v then
                        self.missing[sig.name] = string.format('field "%s" %s', name, why)
                        self.found[sig.name] = nil
                        got = nil
                        break
                    end
                    got[name] = v
                end
                for name, v in pairs(got or {}) do
                    if seen[name] ~= nil and seen[name] ~= v then
                        self.problems[#self.problems + 1] = string.format('"%s" differs between signatures', name)
                        seen[name] = false
                    elseif seen[name] == nil then
                        seen[name] = v
                    end
                end
            end
        end
        for name, v in pairs(seen) do self.values[name] = v or nil end
        self.done = true
    end

    -- The address of a found signature's match (plus an offset), or nil.
    function Scanner:address(name, offset)
        local rva = self.found[name]
        return rva and self.base + rva + (offset or 0)
    end

    -- Every missing signature as 'name (reason)', for logs and status files.
    function Scanner:missing_list()
        local out = {}
        for _, sig in ipairs(self.sigs) do
            if self.missing[sig.name] then out[#out + 1] = sig.name .. ' (' .. self.missing[sig.name] .. ')' end
        end
        return out
    end
end
-- END SIGNATURE ENGINE

---------------------------------------------------------------------------------------
-- Configuration

local OPTION = 'alomare.better_chat.'
local REQUIRED = {'chat_send', 'chat_ring', 'chat_line'}
local RING_SIZE = 64           -- chat history lines (the add-line's index mask is 0x3f)
local COOLDOWN = 2.0           -- seconds between two message sounds
local CHECK_EVERY = 0.2        -- seconds between two reads of the chat history
local MODE_MISSION = 4         -- game mode: 3 ship, 4 mission
-- The sound choice (Mod Options Menu index): the game's own UI sounds, read from the code that plays them; the HUD
-- notices have a value per game mode.
local SOUNDS = {
    {},                        -- OFF
    {key = 'choice.joined', sig = 'join_feed', ship = 'join_ship', mission = 'join_mission'},
    {key = 'choice.left', sig = 'leave_feed', ship = 'leave_ship', mission = 'leave_mission'},
    {key = 'choice.tab', sig = 'tab_button', ship = 'tab_click', mission = 'tab_click'},
    {key = 'choice.subtab', sig = 'button_sounds', ship = 'button_click', mission = 'button_click'},
    {key = 'choice.option', sig = 'option_row', ship = 'option_click', mission = 'option_click'},
}
local DEFAULTS = {sound = 2, volume = 100, layers = false, scale = 100}
local VOLUME = {min = 25, max = 400, step = 25}
local SCALE = {min = 50, max = 200, step = 5}
local NO_SOURCE = 0xffffffff   -- the engine's "no sound source" id
local SCALE_EVERY = 30         -- frames between size checks
local MAX_LOG_LINES = 2000

---------------------------------------------------------------------------------------
-- Logging and status

local function open_log(name)
    if loader and type(loader.open_log) == 'function' then
        local ok, f = pcall(loader.open_log, name)
        if ok then return f end
    end
end

local log_file = open_log('BetterChat.log')
local log_lines = 0

local function note(msg)
    if not log_file or log_lines >= MAX_LOG_LINES then return end
    log_lines = log_lines + 1
    pcall(function()
        log_file:write(string.format('[f%d t%.1f] %s\n', M.frames, os.clock(), msg))
        log_file:flush()
    end)
end

local function write_status(lines)
    local f = open_log('BetterChat_STATUS.log')
    if not f then return end
    pcall(function()
        f:write(table.concat(lines, '\n') .. '\n')
        f:close()
    end)
end

---------------------------------------------------------------------------------------
-- Texts (mod_text: src/bingus_text.lua and locales/, placed ahead of this script by the build)

local T = mod_text.module
local tr = T.new(mod_text.locales.en, mod_text.locales.bundled, function(message) note('Text: ' .. message) end)

-- Mod Options Menu v1.1+ (version 2) takes texts as functions and calls them when its pages open, so the texts
-- follow the game's language; v1.0 takes strings with limits, where a translation that does not fit stays English.
-- One function per key, so repeated registrations agree.
local text_functions = {}
local function host_text(host, functions_from, key, limit)
    if (tonumber(host.version) or 1) >= functions_from then
        local fn = text_functions[key]
        if not fn then fn = function() return tr(key) end; text_functions[key] = fn end
        return fn
    end
    local value = tr(key)
    return #value <= limit and value or tr.english[key]
end

---------------------------------------------------------------------------------------
-- Native access (Windows functions under this mod's own names: no other mod's declarations can change them)

local native = {}

local function init_native()
    if not pcall(ffi.typeof, 'BetterChatVec2') then
        ffi.cdef([[
            typedef struct { float x, y; } BetterChatVec2;
            typedef void (*BetterChatSound)(uint64_t unused, uint32_t id);
            typedef uint32_t (*BetterChatAudioId)(uint32_t id);
            typedef uint64_t (*BetterChatMakeSource)(uint64_t wwise_world);
            typedef uint32_t (*BetterChatPost)(uint64_t wwise_world, uint32_t event, uint64_t source, uint64_t unused);
            typedef void (*BetterChatSetVec)(uint64_t widget, BetterChatVec2 value);
            void *better_chat_GetCurrentProcess(void) __asm__("GetCurrentProcess");
            void *better_chat_GetModuleHandleA(const char *name) __asm__("GetModuleHandleA");
            int better_chat_ReadProcessMemory(void *process, const void *address, void *buffer, size_t size,
                                              size_t *done) __asm__("ReadProcessMemory");
        ]])
    end
    local ok, k32 = pcall(ffi.load, 'kernel32')
    if not ok then return false, 'kernel32 unavailable' end
    native.k32, native.process = k32, k32.better_chat_GetCurrentProcess()
    local game = k32.better_chat_GetModuleHandleA('game.dll')
    if game == nil then return false, 'game.dll not loaded' end
    native.base = tonumber(ffi.cast('uint64_t', game))
    return true
end

local function read(address, size)
    local buf, got = ffi.new('uint8_t[?]', size), ffi.new('size_t[1]')
    if native.k32.better_chat_ReadProcessMemory(native.process, ffi.cast('const void *', address), buf, size, got) == 0
       or tonumber(got[0]) ~= size then
        return nil
    end
    return ffi.string(buf, size)
end

local function u32(blob, offset)
    offset = offset or 0
    if not blob or #blob < offset + 4 then return nil end
    local v = ffi.new('uint32_t[1]')
    ffi.copy(v, blob:sub(offset + 1, offset + 4), 4)
    return tonumber(v[0])
end

local function read32(address) return u32(read(address, 4)) end

local function pointer(blob)
    if not blob or #blob ~= 8 then return nil end
    local v = ffi.new('uint64_t[1]')
    ffi.copy(v, blob, 8)
    local a = tonumber(v[0])
    if a < 0x10000 or a >= 0x800000000000 then return nil end
    return a
end

local function hex(blob)
    if not blob then return 'unreadable' end
    return (blob:reverse():gsub('.', function(c) return string.format('%02x', c:byte()) end))
end

-- Two floats from their 8 bytes.
local function vec_values(blob)
    if not blob or #blob ~= 8 then return nil end
    local v = ffi.new('float[2]')
    ffi.copy(v, blob, 8)
    return tonumber(v[0]), tonumber(v[1])
end

---------------------------------------------------------------------------------------
-- Resolution: signatures -> values and the game's functions

local code = nil  -- the signature engine
local V = {}      -- values read from the matched code (offsets; globals and functions as rvas)
local fn = {}     -- the game's functions that were found
local features = {}  -- feature -> true, or the reason it is off

local function need(names, values)
    for _, name in ipairs(names) do
        if not code.found[name] then return 'code not found: ' .. name .. ' (' .. (code.missing[name] or '?') .. ')' end
    end
    for _, name in ipairs(values or {}) do
        if V[name] == nil then return 'value missing: ' .. name end
    end
end

local function finish_resolution()
    V = code.values
    local missing = code:missing_list()
    local why = need(REQUIRED, {'context', 'chat', 'local_peer', 'ring_first', 'ring_count', 'line_stride',
                                'line_sender'})
    if not why and V.ring_count ~= V.ring_first + 4 then why = 'the ring count does not follow its first index' end
    if not why and V.line_stride < 0x210 then why = 'the chat line is smaller than its text' end
    if why then
        note('Not available: ' .. why .. (#code.problems > 0 and ('; ' .. table.concat(code.problems, ', ')) or ''))
        write_status({'NOT AVAILABLE - ' .. why .. '; the game is unchanged', 'Better Chat ' .. M.version})
        M.retired = true
        return
    end
    if #code.problems > 0 then note('Signature problems: ' .. table.concat(code.problems, ', ')) end
    local base = native.base
    -- The sound: the UI sound function, found by its body and through the calls to it.
    local sound_why = need({'play_sound'})
    if not sound_why and V.ui_sound ~= code.found.play_sound then sound_why = 'the UI sound differs from its calls' end
    if not sound_why then fn.play_sound = ffi.cast('BetterChatSound', base + code.found.play_sound) end
    features.sound = sound_why or true
    -- The volume: the inside of that sound function (its engine calls and the sound id lookup) and the engine's
    -- Lua API for a source's level.
    local volume_why = sound_why or need({'ui_post'}, {'engine', 'make_source', 'ui_world', 'post_event', 'audio_id',
                                                       'game_state'})
    if not volume_why and (code.found.ui_post < code.found.play_sound or code.found.ui_post > code.found.play_sound + 0x40) then
        volume_why = 'the sound source code is not inside the UI sound'
    end
    if not volume_why then
        local S = rawget(_G, 'stingray')
        local wwise, wwise_world = type(S) == 'table' and S.Wwise, type(S) == 'table' and S.WwiseWorld
        if not (wwise and wwise.wwise_world and wwise_world and wwise_world.set_dry_environment_for_source
                and S.Application and S.Application.main_world) then
            volume_why = 'the engine has no source level function'
        end
    end
    if not volume_why then fn.audio_id = ffi.cast('BetterChatAudioId', base + V.audio_id) end
    features.volume = volume_why or true
    -- The size: the chat widget inside the HUD and the widget scale setter.
    local scale_why = need({'chat_notice', 'set_scale'}, {'hud', 'chat_hud'})
    if not scale_why then fn.set_scale = ffi.cast('BetterChatSetVec', base + code.found.set_scale) end
    features.scale = scale_why or true
    M.ready = true
    if #code.moved > 0 then note('Moved code found: ' .. table.concat(code.moved, ', ')) end
    if #missing > 0 then note('Optional code not found: ' .. table.concat(missing, ', ')) end
    local list = {}
    for _, name in ipairs({'sound', 'volume', 'scale'}) do
        list[#list + 1] = name .. ' ' .. (features[name] == true and 'ready' or ('off (' .. features[name] .. ')'))
    end
    local sounds = {}
    for i = 2, #SOUNDS do
        local sound = SOUNDS[i]
        sounds[#sounds + 1] = string.format('%s %s', sound.key:sub(8),
            code.found[sound.sig] and string.format('0x%08x/0x%08x', V[sound.ship], V[sound.mission]) or 'missing')
    end
    note(string.format('Ready: chat = context + 0x%x, ring at +0x%x (stride 0x%x, sender +0x%x); %s; sounds: %s',
                       V.chat, V.ring_first, V.line_stride, V.line_sender, table.concat(list, ', '),
                       table.concat(sounds, ', ')))
    write_status({'OK - watching the chat; ' .. table.concat(list, ', '), 'Better Chat ' .. M.version})
end

---------------------------------------------------------------------------------------
-- Settings (Mod Options Menu, optional; it may load before or after this addon). Without it: the defaults.

local options = {}
for k, v in pairs(DEFAULTS) do options[k] = v end
local menu_state = {menu = nil}
local scale_dirty = true

-- A line before an engine call's first use: an engine assert closes the game, and the log then names the call.
local crumbs = {}
local function crumb(what)
    if crumbs[what] then return end
    crumbs[what] = true
    note('First call: ' .. what)
end

-- A lightuserdata's address ('%p'), or nil.
local function address_of(object)
    local ok, text = pcall(string.format, '%p', object)
    return ok and tonumber((tostring(text):gsub('^0[xX]', '')), 16) or nil
end

-- The engine Lua API's Wwise world at a native address (the game's own), or nil. The main world first; the other
-- worlds only if it is not that one's.
local lua_world = {address = nil, object = nil, failed = nil}
local function lua_wwise_world(address)
    if lua_world.address == address then return lua_world.object end
    if lua_world.failed == address then return nil end
    local S = stingray
    local seen = {}
    local function try(world, what)
        if world == nil then return nil end
        crumb('Wwise.wwise_world (' .. what .. ')')
        local object = S.Wwise.wwise_world(world)
        local at = object ~= nil and address_of(object) or nil
        seen[#seen + 1] = string.format('%s %s 0x%x', what, type(object), at or 0)
        return at == address and object or nil
    end
    crumb('Application.main_world')
    local object = try(S.Application.main_world(), 'main world')
    if not object and S.Application.worlds then
        crumb('Application.worlds')
        for i, world in ipairs(S.Application.worlds() or {}) do
            object = try(world, 'world ' .. i)
            if object then break end
        end
    end
    note(string.format('Wwise world 0x%x in Lua: %s (%s)', address, object and 'found' or 'NOT FOUND',
                       table.concat(seen, '; ')))
    if object then lua_world.address, lua_world.object, lua_world.failed = address, object, nil
    else lua_world.failed = address end
    return object
end

-- Once: what the engine's Lua API offers for sound, and every sound choice's Wwise event id (for the sound banks).
local function log_audio_facts()
    if crumbs.facts then return end
    crumbs.facts = true
    for _, name in ipairs({'Wwise', 'WwiseWorld'}) do
        local keys = {}
        pcall(function() for key in pairs(stingray[name]) do keys[#keys + 1] = tostring(key) end end)
        table.sort(keys)
        note(name .. ' API (' .. type(stingray[name]) .. '): ' .. table.concat(keys, ' '))
    end
    local ids = {}
    for i = 2, #SOUNDS do
        local sound = SOUNDS[i]
        if code.found[sound.sig] then
            ids[#ids + 1] = string.format('%s 0x%08x>%u/0x%08x>%u', sound.key:sub(8), V[sound.ship],
                                          fn.audio_id(V[sound.ship]), V[sound.mission], fn.audio_id(V[sound.mission]))
        end
    end
    note('Wwise events (game id>Wwise id, ship/mission): ' .. table.concat(ids, ', '))
end

-- The sound at another volume: what the game's UI sound function does (a new sound source in the game's Wwise
-- world, the event posted on it), with the source's level set in between. With layers, a volume above 100% is
-- several copies of the sound at once (each at volume / copies), so no source goes above the game's level.
local function play_scaled(id, percent, layered)
    local api = pointer(read(native.base + V.engine, 8))
    local state = pointer(read(native.base + V.game_state, 8))
    local world = state and pointer(read(state + V.ui_world, 8))
    local make = api and pointer(read(api + V.make_source, 8))
    local post = api and pointer(read(api + V.post_event, 8))
    if not (world and make and post) then return false, 'the engine functions are unreadable' end
    log_audio_facts()
    local lua = lua_wwise_world(world)
    if not lua then return false, 'the Wwise world is not in the Lua API' end
    local event = fn.audio_id(id)
    if event == 0 then return false, 'no Wwise event' end
    local copies = (layered and percent > 100) and math.ceil(percent / 100) or 1
    local level = percent / 100 / copies
    make, post = ffi.cast('BetterChatMakeSource', make), ffi.cast('BetterChatPost', post)
    local made = {}
    for k = 1, copies do
        crumb('make source')
        local source = tonumber(make(world))
        if source == NO_SOURCE then return false, 'no sound source' end
        crumb('WwiseWorld.set_dry_environment_for_source')
        stingray.WwiseWorld.set_dry_environment_for_source(lua, source, level)
        crumb('post event')
        made[k] = string.format('source %u playing %u', source, tonumber(post(world, event, source, 0)))
    end
    note(string.format('Scaled sound: Wwise event %u, world 0x%x, %d x level %.3f (%s)', event, world, copies, level,
                       table.concat(made, ', ')))
    return true
end

local function play(choice, why)
    local sound = SOUNDS[choice]
    if not (sound and sound.sig and features.sound == true and code.found[sound.sig]) then return false end
    local state = pointer(read(native.base + V.game_state, 8))
    local mode = state and V.mode and read32(state + V.mode)
    local id = V[mode == MODE_MISSION and sound.mission or sound.ship]
    if not id then return false end
    local scaled = false
    if features.volume == true and options.volume ~= 100 then
        local ok, done, problem = pcall(play_scaled, id, options.volume, options.layers)
        scaled = ok and done
        -- Without it the sound plays as the game does; after an error the volume stays off.
        if not scaled then note('Volume not applied: ' .. tostring(ok and problem or done)) end
        if not ok then features.volume = 'error: ' .. tostring(done) end
    end
    if not scaled then fn.play_sound(0, id) end
    note(string.format('Sound 0x%08x (%s, mode %s, volume %s)', id, why, tostring(mode),
                       scaled and (options.volume .. '%') or 'game'))
    return true
end

local function clamp(v, range, default)
    return math.max(range.min, math.min(range.max, tonumber(v) or default))
end

local SETTERS = {
    sound = function(v) v = math.floor(tonumber(v) or DEFAULTS.sound); return (v >= 1 and v <= #SOUNDS) and v or DEFAULTS.sound end,
    volume = function(v) return clamp(v, VOLUME, DEFAULTS.volume) end,
    layers = function(v) return v == true end,
    scale = function(v) return clamp(v, SCALE, DEFAULTS.scale) end,
}

local function set_option(name, value, applied)
    local v = SETTERS[name](value)
    if v ~= options[name] then note(string.format('Option %s = %s', name, tostring(v))) end
    options[name] = v
    if name == 'scale' then scale_dirty = true end
    -- A sound or a volume picked in the menu plays once, so it can be heard.
    if name ~= 'scale' and applied and M.ready then play(options.sound, 'preview') end
end

local function connect_options()
    local menu = rawget(_G, 'ModOptionsMenu')
    if type(menu) ~= 'table' or menu.api ~= 1 then return end
    menu_state.menu = menu
    local function text(key, limit) return host_text(menu, 2, key, limit) end
    local mod = text('option.mod', 40)
    local choices = {}
    for i, sound in ipairs(SOUNDS) do choices[i] = i == 1 and 'OFF' or text(sound.key, 48) end
    local specs = {
        {'sound', {type = 'choice', choices = choices, default = DEFAULTS.sound}},
        {'volume', {type = 'slider', min = VOLUME.min, max = VOLUME.max, step = VOLUME.step,
                    default = DEFAULTS.volume}},
        -- Test build only: how a volume above 100% is made.
        {'layers', {type = 'toggle', default = DEFAULTS.layers, label = 'Volume Test: Layers',
                    description = 'Test build only. OFF: above 100%, the sound is one copy at a higher level. ON: '
                        .. 'above 100%, it is several copies at once. Try 200% and 400% both ways and tell which '
                        .. 'gets louder.'}},
        {'scale', {type = 'slider', min = SCALE.min, max = SCALE.max, step = SCALE.step, default = DEFAULTS.scale}},
    }
    for _, entry in ipairs(specs) do
        local name, spec = entry[1], entry[2]
        local id = OPTION .. name
        spec.mod, spec.mod_id = mod, 'alomare.better_chat'
        spec.label = spec.label or text('option.' .. name .. '.label', 64)
        spec.description = spec.description or text('option.' .. name .. '.description', 400)
        local ok, done, why = pcall(menu.register_option, id, spec)
        if ok and done then
            pcall(menu.on_change, id, function(value) set_option(name, value, true) end)
            local got, value = pcall(menu.get, id)
            if got and value ~= nil then set_option(name, value, false) end
        else
            note('Option ' .. id .. ' not registered: ' .. tostring(ok and why or done))
        end
    end
    note('Mod Options Menu connected (version ' .. tostring(menu.version or 1) .. ')')
end

---------------------------------------------------------------------------------------
-- New chat lines

local ring = {ctx = nil, first = 0, count = 0}
local clock, last_sound, last_check = 0, -math.huge, -math.huge

local function alert(others, total)
    note(string.format('%d new chat line(s), %d from other players', total, others))
    if others == 0 or options.sound == 1 then return end
    if clock - last_sound >= COOLDOWN then
        if play(options.sound, 'new message') then last_sound = clock end
    else
        note('Sound skipped (cooldown)')
    end
end

-- The chat line flags the game keeps per line, after the sender and text (diagnostics): friend, shown, filtered,
-- and two display bytes.
local LINE_FLAGS = 0x209       -- from the sender (0xda1 - 0xb98 in this build)
local function line_flags(chat, slot)
    local b = read(chat + V.line_sender + LINE_FLAGS + slot * V.line_stride, 5)
    if not b then return '?' end
    return string.format('%d%d%d%d%d', b:byte(1, 5))
end

local function watch_chat()
    local ctx = pointer(read(native.base + V.context, 8))
    if not ctx then
        if ring.ctx then note('Network context gone'); ring.ctx = nil end
        return
    end
    local chat = ctx + V.chat
    local header = read(chat + V.ring_first, 8)
    local first, count = u32(header, 0), u32(header, 4)
    if not first or first >= RING_SIZE or count > RING_SIZE then return end
    if ring.ctx ~= ctx or count < ring.count then
        -- A new session or a cleared history: lines already there are not new.
        note(string.format('Chat history: context 0x%x, first %d, count %d', ctx, first, count))
        ring.ctx, ring.first, ring.count = ctx, first, count
        return
    end
    local new = (count - ring.count) + (first - ring.first) % RING_SIZE
    ring.first, ring.count = first, count
    if new <= 0 then return end
    new = math.min(new, RING_SIZE)
    local own = read(ctx + V.local_peer, 8)
    local others = 0
    for k = new, 1, -1 do
        local slot = (first + count - k) % RING_SIZE
        local sender = read(chat + V.line_sender + slot * V.line_stride, 8)
        local text = read(chat + V.line_text + slot * V.line_stride, 0x200)
        local length = text and (text:find('\0', 1, true) or 0x201) - 1 or -1
        local from_other = sender ~= nil and own ~= nil and sender ~= own
        if from_other then others = others + 1 end
        note(string.format('Line %d: sender %s%s, %d bytes, flags %s', slot, hex(sender),
                           from_other and '' or ' (you)', length, line_flags(chat, slot)))
    end
    alert(others, new)
end

---------------------------------------------------------------------------------------
-- Chat size

local layout = {scale_base = nil, scaled = false, logged = false}

local function near(a, b) return math.abs(a - b) < 1e-4 end

local function apply_scale()
    local hud = pointer(read(native.base + V.hud, 8))
    if not hud then return end
    local widget = hud + V.chat_hud
    local sx, sy = vec_values(read(widget + 0x14, 8))
    -- A widget not laid out yet has scale 0: wait for it.
    if not sx or sx <= 0 or sy <= 0 then return end
    if not layout.logged then
        layout.logged = true
        note(string.format('Chat widget 0x%x: scale (%.3f, %.3f)', widget, sx, sy))
    end
    if not layout.scaled then layout.scale_base = {sx, sy} end
    local want = options.scale / 100
    local wx, wy = layout.scale_base[1] * want, layout.scale_base[2] * want
    if (layout.scaled or options.scale ~= 100) and not (near(sx, wx) and near(sy, wy)) then
        fn.set_scale(widget, ffi.new('BetterChatVec2', wx, wy))
        layout.scaled = options.scale ~= 100
        note(string.format('Chat scale (%.3f, %.3f) -> (%.3f, %.3f)', sx, sy, wx, wy))
    end
end

---------------------------------------------------------------------------------------
-- Frame step

local function start()
    M.started = true
    local ok, why = init_native()
    if not ok then
        write_status({'NOT AVAILABLE - ' .. why .. '; the game is unchanged', 'Better Chat ' .. M.version})
        note('Native access unavailable: ' .. why)
        M.retired = true
        return
    end
    -- The game's Text Language, for this mod's texts and every other mod's (bingus_text's shared registry).
    local tag, game_code = T.observe(read, native.base)
    note('Text language: ' .. tostring(T.language()) .. ' (game setting ' .. tostring(game_code or 'unreadable')
         .. ', tag ' .. tostring(tag) .. ')')
    code = sigscan.new(SIGS, read, native.base)
    local all, reason = code:start()
    if all == nil then
        write_status({'NOT AVAILABLE - ' .. reason .. '; the game is unchanged', 'Better Chat ' .. M.version})
        M.retired = true
    elseif all then
        finish_resolution()
    else
        note('Searching game.dll for moved code (game updated?)')
    end
end

local function frame(dt)
    M.frames = M.frames + 1
    clock = clock + (tonumber(dt) or 0)
    if not menu_state.menu then connect_options() end
    if not M.started then start(); return end
    if not M.ready then
        if code.scan and code:step() then finish_resolution() end
        return
    end
    if clock - last_check >= CHECK_EVERY then
        last_check = clock
        watch_chat()
    end
    if features.scale == true and (scale_dirty or M.frames % SCALE_EVERY == 0) then
        scale_dirty = false
        apply_scale()
    end
end

local original_update = rawget(_G, 'update')
update = function(dt, ...)
    if not M.retired then
        local ok, err = xpcall(frame, debug.traceback, dt)
        if not ok then
            M.errors = M.errors + 1
            note('Error: ' .. tostring(err))
            if M.errors >= 5 then
                M.retired = true
                write_status({'STOPPED - repeated errors (see BetterChat.log)', 'Better Chat ' .. M.version})
            end
        end
    end
    if type(original_update) == 'function' then return original_update(dt, ...) end
end

note('Better Chat ' .. M.version .. ' loaded')
M._test = {values = function() return V end, features = function() return features end,
           options = function() return options end}  -- offline checks
return M
